/** Generated by game/scripts/build-embed-lesson.mjs. Picture numbers are copied from embed/demo/results.json. */
export const EMBED_PAGES = [
  {
    "id": "e1-intro",
    "chapter": 1,
    "kind": "intro",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "hat"
        },
        "ja": {
          "kind": "hat"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e1-intro.bubble",
      "aim": "e1-intro.aim",
      "look": "e1-intro.look",
      "action": "e1-intro.action",
      "summary": "e1-intro.summary",
      "talk": "e1-intro.talk",
      "checkQ": "e1-intro.checkQ",
      "checkA": "e1-intro.checkA",
      "vo": "e1-intro.vo",
      "art": "e1-intro.art"
    }
  },
  {
    "id": "e1-p1",
    "chapter": 1,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "strip",
          "dim": 384,
          "item": {
            "word": "早饭",
            "label": "早饭",
            "cells": [
              "b",
              "b",
              "r",
              "r",
              "p",
              "p",
              "r",
              "b"
            ]
          }
        },
        "ja": {
          "kind": "strip",
          "dim": 384,
          "item": {
            "word": "breakfast",
            "label": "朝ごはん〔breakfast〕",
            "cells": [
              "b",
              "b",
              "r",
              "r",
              "r",
              "p",
              "r",
              "b"
            ]
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e1-p1.bubble",
      "aim": "e1-p1.aim",
      "look": "e1-p1.look",
      "action": "e1-p1.action",
      "summary": "e1-p1.summary",
      "talk": "e1-p1.talk",
      "checkQ": "e1-p1.checkQ",
      "checkA": "e1-p1.checkA",
      "vo": "e1-p1.vo",
      "art": "e1-p1.art"
    }
  },
  {
    "id": "e1-p2",
    "chapter": 1,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "align",
          "dim": 384,
          "items": [
            {
              "word": "狗",
              "label": "狗",
              "cells": [
                "p",
                "p",
                "p",
                "p",
                "p",
                "p",
                "p",
                "p"
              ],
              "measured": false
            },
            {
              "word": "停车",
              "label": "停车",
              "cells": [
                "r",
                "r",
                "p",
                "p",
                "r",
                "r",
                "r",
                "r"
              ],
              "measured": true
            },
            {
              "word": "游泳池",
              "label": "游泳池",
              "cells": [
                "p",
                "p",
                "p",
                "p",
                "p",
                "p",
                "p",
                "p"
              ],
              "measured": false
            }
          ]
        },
        "ja": {
          "kind": "align",
          "dim": 384,
          "items": [
            {
              "word": "dog",
              "label": "犬〔dog〕",
              "cells": [
                "p",
                "p",
                "p",
                "p",
                "p",
                "p",
                "p",
                "p"
              ],
              "measured": false
            },
            {
              "word": "parking",
              "label": "ちゅうしゃ〔parking〕",
              "cells": [
                "r",
                "r",
                "p",
                "p",
                "p",
                "p",
                "r",
                "r"
              ],
              "measured": true
            },
            {
              "word": "swimming pool",
              "label": "水泳プール〔swimming pool〕",
              "cells": [
                "p",
                "p",
                "p",
                "p",
                "p",
                "p",
                "p",
                "p"
              ],
              "measured": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e1-p2.bubble",
      "aim": "e1-p2.aim",
      "look": "e1-p2.look",
      "action": "e1-p2.action",
      "summary": "e1-p2.summary",
      "talk": "e1-p2.talk",
      "checkQ": "e1-p2.checkQ",
      "checkA": "e1-p2.checkA",
      "vo": "e1-p2.vo",
      "art": "e1-p2.art"
    }
  },
  {
    "id": "e1-p3",
    "chapter": 1,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "compare",
          "items": [
            {
              "word": "早饭",
              "label": "早饭",
              "cells": [
                "b",
                "b",
                "r",
                "r",
                "p",
                "p",
                "r",
                "b"
              ]
            },
            {
              "word": "早餐",
              "label": "早餐",
              "cells": [
                "b",
                "b",
                "r",
                "r",
                "p",
                "p",
                "r",
                "b"
              ]
            },
            {
              "word": "停车",
              "label": "停车",
              "cells": [
                "r",
                "r",
                "p",
                "p",
                "r",
                "r",
                "r",
                "r"
              ]
            }
          ]
        },
        "ja": {
          "kind": "compare",
          "items": [
            {
              "word": "breakfast",
              "label": "朝ごはん〔breakfast〕",
              "cells": [
                "b",
                "b",
                "r",
                "r",
                "r",
                "p",
                "r",
                "b"
              ]
            },
            {
              "word": "morning meal",
              "label": "朝の 食事〔morning meal〕",
              "cells": [
                "p",
                "b",
                "r",
                "r",
                "p",
                "b",
                "r",
                "b"
              ]
            },
            {
              "word": "parking",
              "label": "ちゅうしゃ〔parking〕",
              "cells": [
                "r",
                "r",
                "p",
                "p",
                "p",
                "p",
                "r",
                "r"
              ]
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e1-p3.bubble",
      "aim": "e1-p3.aim",
      "look": "e1-p3.look",
      "action": "e1-p3.action",
      "summary": "e1-p3.summary",
      "talk": "e1-p3.talk",
      "checkQ": "e1-p3.checkQ",
      "checkA": "e1-p3.checkA",
      "vo": "e1-p3.vo",
      "art": "e1-p3.art"
    }
  },
  {
    "id": "e1-p4",
    "chapter": 1,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "tags",
          "tags": [
            "向量",
            "词向量",
            "意思的地址"
          ]
        },
        "ja": {
          "kind": "tags",
          "tags": [
            "ベクトル",
            "単語ベクトル",
            "いみの じゅうしょ"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e1-p4.bubble",
      "aim": "e1-p4.aim",
      "look": "e1-p4.look",
      "action": "e1-p4.action",
      "summary": "e1-p4.summary",
      "talk": "e1-p4.talk",
      "checkQ": "e1-p4.checkQ",
      "checkA": "e1-p4.checkA",
      "vo": "e1-p4.vo",
      "art": "e1-p4.art"
    }
  },
  {
    "id": "e1-p5",
    "chapter": 1,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "class",
          "dim": 384,
          "showSame": true,
          "same": 7,
          "cells": 8,
          "items": [
            {
              "word": "早饭",
              "label": "早饭",
              "cells": [
                "b",
                "b",
                "r",
                "r",
                "p",
                "p",
                "r",
                "b"
              ]
            },
            {
              "word": "breakfast",
              "label": "breakfast",
              "cells": [
                "b",
                "b",
                "r",
                "r",
                "r",
                "p",
                "r",
                "b"
              ]
            }
          ]
        },
        "ja": {
          "kind": "class",
          "dim": 384,
          "showSame": false,
          "same": 8,
          "cells": 8,
          "items": [
            {
              "word": "breakfast",
              "label": "朝ごはん〔breakfast〕",
              "cells": [
                "b",
                "b",
                "r",
                "r",
                "r",
                "p",
                "r",
                "b"
              ]
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e1-p5.bubble",
      "aim": "e1-p5.aim",
      "look": "e1-p5.look",
      "action": "e1-p5.action",
      "summary": "e1-p5.summary",
      "talk": "e1-p5.talk",
      "checkQ": "e1-p5.checkQ",
      "checkA": "e1-p5.checkA",
      "vo": "e1-p5.vo",
      "art": "e1-p5.art"
    }
  },
  {
    "id": "e1-sum",
    "chapter": 1,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "一个词进了小窗，变成一排数字，画成彩色带子。",
            "每个词、每张卡，都是 384 个数字。",
            "意思像的词，带子也像。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "語は まどに 入ると 数字の ならびに なり、色の おびで かけます。",
            "どの 語も、どの カードも、384この 数字です。",
            "いみが にて いる 語は、おびも にて います。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e1-sum.bubble",
      "aim": "e1-sum.aim",
      "look": "e1-sum.look",
      "action": "e1-sum.action",
      "summary": "e1-sum.summary",
      "talk": "e1-sum.talk",
      "checkQ": "e1-sum.checkQ",
      "checkA": "e1-sum.checkA",
      "vo": "e1-sum.vo",
      "art": "e1-sum.art",
      "star1": "e1-sum.star1",
      "star2": "e1-sum.star2",
      "star3": "e1-sum.star3"
    }
  },
  {
    "id": "e1-rev",
    "chapter": 1,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e1-rev.bubble",
      "aim": "e1-rev.aim",
      "look": "e1-rev.look",
      "action": "e1-rev.action",
      "summary": "e1-rev.summary",
      "talk": "e1-rev.talk",
      "checkQ": "e1-rev.checkQ",
      "checkA": "e1-rev.checkA",
      "vo": "e1-rev.vo",
      "art": "e1-rev.art",
      "star1": "e1-rev.star1",
      "star2": "e1-rev.star2",
      "star3": "e1-rev.star3"
    }
  },
  {
    "id": "e2-intro",
    "chapter": 2,
    "kind": "intro",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "beans",
          "count": 20
        },
        "ja": {
          "kind": "beans",
          "count": 20
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e2-intro.bubble",
      "aim": "e2-intro.aim",
      "look": "e2-intro.look",
      "action": "e2-intro.action",
      "summary": "e2-intro.summary",
      "talk": "e2-intro.talk",
      "checkQ": "e2-intro.checkQ",
      "checkA": "e2-intro.checkA",
      "vo": "e2-intro.vo",
      "art": "e2-intro.art"
    }
  },
  {
    "id": "e2-p1",
    "chapter": 2,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "map",
          "mapKey": "zh",
          "groups": [
            {
              "name": "吃饭村",
              "words": [
                {
                  "word": "早饭",
                  "label": "早饭"
                },
                {
                  "word": "早餐",
                  "label": "早餐"
                },
                {
                  "word": "午饭",
                  "label": "午饭"
                },
                {
                  "word": "晚饭",
                  "label": "晚饭"
                }
              ]
            },
            {
              "name": "游泳村",
              "words": [
                {
                  "word": "游泳",
                  "label": "游泳"
                },
                {
                  "word": "泳池",
                  "label": "泳池"
                },
                {
                  "word": "游泳池",
                  "label": "游泳池"
                }
              ]
            },
            {
              "name": "车子村",
              "words": [
                {
                  "word": "停车",
                  "label": "停车"
                },
                {
                  "word": "车位",
                  "label": "车位"
                },
                {
                  "word": "停车场",
                  "label": "停车场"
                },
                {
                  "word": "车",
                  "label": "车"
                }
              ]
            },
            {
              "name": "小狗村",
              "words": [
                {
                  "word": "狗",
                  "label": "狗"
                },
                {
                  "word": "小狗",
                  "label": "小狗"
                }
              ]
            },
            {
              "name": "前台村",
              "words": [
                {
                  "word": "退房",
                  "label": "退房"
                },
                {
                  "word": "入住",
                  "label": "入住"
                },
                {
                  "word": "前台",
                  "label": "前台"
                },
                {
                  "word": "钥匙",
                  "label": "钥匙"
                },
                {
                  "word": "猫",
                  "label": "猫"
                }
              ]
            },
            {
              "name": "中间",
              "words": [
                {
                  "word": "毛巾",
                  "label": "毛巾"
                },
                {
                  "word": "枕头",
                  "label": "枕头"
                }
              ]
            }
          ]
        },
        "ja": {
          "kind": "map",
          "mapKey": "en",
          "groups": [
            {
              "name": "ごはん村",
              "words": [
                {
                  "word": "breakfast",
                  "label": "朝ごはん〔breakfast〕"
                },
                {
                  "word": "morning meal",
                  "label": "朝の 食事〔morning meal〕"
                },
                {
                  "word": "lunch",
                  "label": "昼ごはん〔lunch〕"
                },
                {
                  "word": "dinner",
                  "label": "夕ごはん〔dinner〕"
                }
              ]
            },
            {
              "name": "およぎ村",
              "words": [
                {
                  "word": "swim",
                  "label": "およぐ〔swim〕"
                },
                {
                  "word": "swimming",
                  "label": "およぎ〔swimming〕"
                },
                {
                  "word": "pool",
                  "label": "プール〔pool〕"
                },
                {
                  "word": "swimming pool",
                  "label": "水泳プール〔swimming pool〕"
                }
              ]
            },
            {
              "name": "くるま村",
              "words": [
                {
                  "word": "parking",
                  "label": "ちゅうしゃ〔parking〕"
                },
                {
                  "word": "parking lot",
                  "label": "ちゅうしゃじょう〔parking lot〕"
                },
                {
                  "word": "car",
                  "label": "車〔car〕"
                }
              ]
            },
            {
              "name": "どうぶつ村",
              "words": [
                {
                  "word": "dog",
                  "label": "犬〔dog〕"
                },
                {
                  "word": "dogs",
                  "label": "犬たち〔dogs〕"
                },
                {
                  "word": "cat",
                  "label": "ねこ〔cat〕"
                }
              ]
            },
            {
              "name": "フロント村",
              "words": [
                {
                  "word": "key",
                  "label": "かぎ〔key〕"
                },
                {
                  "word": "checkout",
                  "label": "チェックアウト〔checkout〕"
                },
                {
                  "word": "check-in",
                  "label": "チェックイン〔check-in〕"
                },
                {
                  "word": "front desk",
                  "label": "フロント〔front desk〕"
                }
              ]
            },
            {
              "name": "まんなか",
              "words": [
                {
                  "word": "towel",
                  "label": "タオル〔towel〕"
                },
                {
                  "word": "pillow",
                  "label": "まくら〔pillow〕"
                }
              ]
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e2-p1.bubble",
      "aim": "e2-p1.aim",
      "look": "e2-p1.look",
      "action": "e2-p1.action",
      "summary": "e2-p1.summary",
      "talk": "e2-p1.talk",
      "checkQ": "e2-p1.checkQ",
      "checkA": "e2-p1.checkA",
      "vo": "e2-p1.vo",
      "art": "e2-p1.art"
    }
  },
  {
    "id": "e2-p2",
    "chapter": 2,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "podium",
          "items": [
            {
              "a": "早饭",
              "b": "早餐",
              "aLabel": "早饭",
              "bLabel": "早餐",
              "points": 99
            },
            {
              "a": "早饭",
              "b": "午饭",
              "aLabel": "早饭",
              "bLabel": "午饭",
              "points": 68
            },
            {
              "a": "早饭",
              "b": "停车",
              "aLabel": "早饭",
              "bLabel": "停车",
              "points": 32
            }
          ]
        },
        "ja": {
          "kind": "podium",
          "items": [
            {
              "a": "breakfast",
              "b": "morning meal",
              "aLabel": "朝ごはん〔breakfast〕",
              "bLabel": "朝の 食事〔morning meal〕",
              "points": 89
            },
            {
              "a": "breakfast",
              "b": "lunch",
              "aLabel": "朝ごはん〔breakfast〕",
              "bLabel": "昼ごはん〔lunch〕",
              "points": 72
            },
            {
              "a": "breakfast",
              "b": "parking",
              "aLabel": "朝ごはん〔breakfast〕",
              "bLabel": "ちゅうしゃ〔parking〕",
              "points": 14
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e2-p2.bubble",
      "aim": "e2-p2.aim",
      "look": "e2-p2.look",
      "action": "e2-p2.action",
      "summary": "e2-p2.summary",
      "talk": "e2-p2.talk",
      "checkQ": "e2-p2.checkQ",
      "checkA": "e2-p2.checkA",
      "vo": "e2-p2.vo",
      "art": "e2-p2.art"
    }
  },
  {
    "id": "e2-p3",
    "chapter": 2,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "ropes",
          "items": [
            {
              "a": "停车",
              "b": "车位",
              "aLabel": "停车",
              "bLabel": "车位",
              "points": 77
            },
            {
              "a": "游泳",
              "b": "泳池",
              "aLabel": "游泳",
              "bLabel": "泳池",
              "points": 78
            },
            {
              "a": "狗",
              "b": "小狗",
              "aLabel": "狗",
              "bLabel": "小狗",
              "points": 97
            },
            {
              "a": "狗",
              "b": "游泳",
              "aLabel": "狗",
              "bLabel": "游泳",
              "points": 16
            }
          ]
        },
        "ja": {
          "kind": "ropes",
          "items": [
            {
              "a": "parking",
              "b": "parking lot",
              "aLabel": "ちゅうしゃ〔parking〕",
              "bLabel": "ちゅうしゃじょう〔parking lot〕",
              "points": 89
            },
            {
              "a": "swim",
              "b": "swimming",
              "aLabel": "およぐ〔swim〕",
              "bLabel": "およぎ〔swimming〕",
              "points": 97
            },
            {
              "a": "dog",
              "b": "dogs",
              "aLabel": "犬〔dog〕",
              "bLabel": "犬たち〔dogs〕",
              "points": 91
            },
            {
              "a": "dog",
              "b": "swim",
              "aLabel": "犬〔dog〕",
              "bLabel": "およぐ〔swim〕",
              "points": 14
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e2-p3.bubble",
      "aim": "e2-p3.aim",
      "look": "e2-p3.look",
      "action": "e2-p3.action",
      "summary": "e2-p3.summary",
      "talk": "e2-p3.talk",
      "checkQ": "e2-p3.checkQ",
      "checkA": "e2-p3.checkA",
      "vo": "e2-p3.vo",
      "art": "e2-p3.art"
    }
  },
  {
    "id": "e2-p4",
    "chapter": 2,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rings",
          "groups": [
            {
              "focus": "早饭",
              "word": "早饭",
              "items": [
                {
                  "word": "早餐",
                  "label": "早餐",
                  "points": 99
                },
                {
                  "word": "午饭",
                  "label": "午饭",
                  "points": 68
                },
                {
                  "word": "晚饭",
                  "label": "晚饭",
                  "points": 61
                }
              ]
            },
            {
              "focus": "游泳池",
              "word": "游泳池",
              "items": [
                {
                  "word": "泳池",
                  "label": "泳池",
                  "points": 99
                },
                {
                  "word": "游泳",
                  "label": "游泳",
                  "points": 80
                },
                {
                  "word": "毛巾",
                  "label": "毛巾",
                  "points": 43
                }
              ]
            }
          ]
        },
        "ja": {
          "kind": "rings",
          "groups": [
            {
              "focus": "朝ごはん〔breakfast〕",
              "word": "breakfast",
              "items": [
                {
                  "word": "morning meal",
                  "label": "朝の 食事〔morning meal〕",
                  "points": 89
                },
                {
                  "word": "lunch",
                  "label": "昼ごはん〔lunch〕",
                  "points": 72
                },
                {
                  "word": "dinner",
                  "label": "夕ごはん〔dinner〕",
                  "points": 63
                }
              ]
            },
            {
              "focus": "水泳プール〔swimming pool〕",
              "word": "swimming pool",
              "items": [
                {
                  "word": "pool",
                  "label": "プール〔pool〕",
                  "points": 88
                },
                {
                  "word": "swimming",
                  "label": "およぎ〔swimming〕",
                  "points": 78
                },
                {
                  "word": "swim",
                  "label": "およぐ〔swim〕",
                  "points": 73
                }
              ]
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e2-p4.bubble",
      "aim": "e2-p4.aim",
      "look": "e2-p4.look",
      "action": "e2-p4.action",
      "summary": "e2-p4.summary",
      "talk": "e2-p4.talk",
      "checkQ": "e2-p4.checkQ",
      "checkA": "e2-p4.checkA",
      "vo": "e2-p4.vo",
      "art": "e2-p4.art"
    }
  },
  {
    "id": "e2-p5",
    "chapter": 2,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "merge",
          "items": [
            {
              "a": "早饭",
              "b": "breakfast",
              "aLabel": "早饭",
              "bLabel": "breakfast",
              "points": 98
            },
            {
              "a": "狗",
              "b": "dog",
              "aLabel": "狗",
              "bLabel": "dog",
              "points": 97
            },
            {
              "a": "游泳池",
              "b": "swimming pool",
              "aLabel": "游泳池",
              "bLabel": "swimming pool",
              "points": 93
            },
            {
              "a": "早饭",
              "b": "dog",
              "aLabel": "早饭",
              "bLabel": "dog",
              "points": 9
            }
          ]
        },
        "ja": {
          "kind": "merge",
          "items": [
            {
              "a": "朝ごはん",
              "b": "breakfast",
              "aLabel": "朝ごはん",
              "bLabel": "朝ごはん〔breakfast〕",
              "points": 95
            },
            {
              "a": "犬",
              "b": "dog",
              "aLabel": "犬",
              "bLabel": "犬〔dog〕",
              "points": 98
            },
            {
              "a": "駐車場",
              "b": "parking lot",
              "aLabel": "駐車場",
              "bLabel": "ちゅうしゃじょう〔parking lot〕",
              "points": 91
            },
            {
              "a": "プール",
              "b": "pool",
              "aLabel": "プール",
              "bLabel": "プール〔pool〕",
              "points": 84
            },
            {
              "a": "朝ごはん",
              "b": "dog",
              "aLabel": "朝ごはん",
              "bLabel": "犬〔dog〕",
              "points": 9
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e2-p5.bubble",
      "aim": "e2-p5.aim",
      "look": "e2-p5.look",
      "action": "e2-p5.action",
      "summary": "e2-p5.summary",
      "talk": "e2-p5.talk",
      "checkQ": "e2-p5.checkQ",
      "checkA": "e2-p5.checkA",
      "vo": "e2-p5.vo",
      "art": "e2-p5.art"
    }
  },
  {
    "id": "e2-sum",
    "chapter": 2,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "意思像的词，在地图上是邻居。",
            "近分说出有多近：分越高越近，显示 100 分可能是取整，不能证明完全一样。",
            "字不一样也能很近（停车 和 车位 77 分）。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "いみが にて いる 語は、地図の 上で おとなりどうし。",
            "近さの 点数で どれくらい 近いか 言える。高いほど 近く、100てんは 丸めた 表示なので、厳密に 同じとは 限りません。",
            "字が ちがっても 近く なれる（およぐ と およぎ 97てん）。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e2-sum.bubble",
      "aim": "e2-sum.aim",
      "look": "e2-sum.look",
      "action": "e2-sum.action",
      "summary": "e2-sum.summary",
      "talk": "e2-sum.talk",
      "checkQ": "e2-sum.checkQ",
      "checkA": "e2-sum.checkA",
      "vo": "e2-sum.vo",
      "art": "e2-sum.art",
      "star1": "e2-sum.star1",
      "star2": "e2-sum.star2",
      "star3": "e2-sum.star3"
    }
  },
  {
    "id": "e2-rev",
    "chapter": 2,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e2-rev.bubble",
      "aim": "e2-rev.aim",
      "look": "e2-rev.look",
      "action": "e2-rev.action",
      "summary": "e2-rev.summary",
      "talk": "e2-rev.talk",
      "checkQ": "e2-rev.checkQ",
      "checkA": "e2-rev.checkA",
      "vo": "e2-rev.vo",
      "art": "e2-rev.art",
      "star1": "e2-rev.star1",
      "star2": "e2-rev.star2",
      "star3": "e2-rev.star3"
    }
  },
  {
    "id": "e3-intro",
    "chapter": 3,
    "kind": "intro",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "fan"
        },
        "ja": {
          "kind": "fan"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e3-intro.bubble",
      "aim": "e3-intro.aim",
      "look": "e3-intro.look",
      "action": "e3-intro.action",
      "summary": "e3-intro.summary",
      "talk": "e3-intro.talk",
      "checkQ": "e3-intro.checkQ",
      "checkA": "e3-intro.checkA",
      "vo": "e3-intro.vo",
      "art": "e3-intro.art"
    }
  },
  {
    "id": "e3-p1",
    "chapter": 3,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "arrows",
          "dim": 384,
          "words": [
            "早饭",
            "停车"
          ]
        },
        "ja": {
          "kind": "arrows",
          "dim": 384,
          "words": [
            "breakfast",
            "parking"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e3-p1.bubble",
      "aim": "e3-p1.aim",
      "look": "e3-p1.look",
      "action": "e3-p1.action",
      "summary": "e3-p1.summary",
      "talk": "e3-p1.talk",
      "checkQ": "e3-p1.checkQ",
      "checkA": "e3-p1.checkA",
      "vo": "e3-p1.vo",
      "art": "e3-p1.art"
    }
  },
  {
    "id": "e3-p2",
    "chapter": 3,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "circle",
          "dim": 384
        },
        "ja": {
          "kind": "circle",
          "dim": 384
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e3-p2.bubble",
      "aim": "e3-p2.aim",
      "look": "e3-p2.look",
      "action": "e3-p2.action",
      "summary": "e3-p2.summary",
      "talk": "e3-p2.talk",
      "checkQ": "e3-p2.checkQ",
      "checkA": "e3-p2.checkA",
      "vo": "e3-p2.vo",
      "art": "e3-p2.art"
    }
  },
  {
    "id": "e3-p3",
    "chapter": 3,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "angles",
          "items": [
            {
              "a": "早饭",
              "b": "早餐",
              "aLabel": "早饭",
              "bLabel": "早餐",
              "points": 99
            },
            {
              "a": "早饭",
              "b": "午饭",
              "aLabel": "早饭",
              "bLabel": "午饭",
              "points": 68
            },
            {
              "a": "狗",
              "b": "游泳",
              "aLabel": "狗",
              "bLabel": "游泳",
              "points": 16
            }
          ]
        },
        "ja": {
          "kind": "angles",
          "items": [
            {
              "a": "breakfast",
              "b": "morning meal",
              "aLabel": "朝ごはん〔breakfast〕",
              "bLabel": "朝の 食事〔morning meal〕",
              "points": 89
            },
            {
              "a": "breakfast",
              "b": "lunch",
              "aLabel": "朝ごはん〔breakfast〕",
              "bLabel": "昼ごはん〔lunch〕",
              "points": 72
            },
            {
              "a": "dog",
              "b": "swim",
              "aLabel": "犬〔dog〕",
              "bLabel": "およぐ〔swim〕",
              "points": 14
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e3-p3.bubble",
      "aim": "e3-p3.aim",
      "look": "e3-p3.look",
      "action": "e3-p3.action",
      "summary": "e3-p3.summary",
      "talk": "e3-p3.talk",
      "checkQ": "e3-p3.checkQ",
      "checkA": "e3-p3.checkA",
      "vo": "e3-p3.vo",
      "art": "e3-p3.art"
    }
  },
  {
    "id": "e3-p4",
    "chapter": 3,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "ruler",
          "items": [
            {
              "a": "早饭",
              "b": "早餐",
              "aLabel": "早饭",
              "bLabel": "早餐",
              "points": 99
            },
            {
              "a": "早饭",
              "b": "午饭",
              "aLabel": "早饭",
              "bLabel": "午饭",
              "points": 68
            },
            {
              "a": "狗",
              "b": "游泳",
              "aLabel": "狗",
              "bLabel": "游泳",
              "points": 16
            }
          ],
          "marks": [
            100,
            50,
            0
          ],
          "card": {
            "pages": [
              4,
              5
            ],
            "points": 80,
            "label": "早饭卡–晚饭卡"
          }
        },
        "ja": {
          "kind": "ruler",
          "items": [
            {
              "a": "breakfast",
              "b": "morning meal",
              "aLabel": "朝ごはん〔breakfast〕",
              "bLabel": "朝の 食事〔morning meal〕",
              "points": 89
            },
            {
              "a": "breakfast",
              "b": "lunch",
              "aLabel": "朝ごはん〔breakfast〕",
              "bLabel": "昼ごはん〔lunch〕",
              "points": 72
            },
            {
              "a": "dog",
              "b": "swim",
              "aLabel": "犬〔dog〕",
              "bLabel": "およぐ〔swim〕",
              "points": 14
            }
          ],
          "marks": [
            100,
            50,
            0
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e3-p4.bubble",
      "aim": "e3-p4.aim",
      "look": "e3-p4.look",
      "action": "e3-p4.action",
      "summary": "e3-p4.summary",
      "talk": "e3-p4.talk",
      "checkQ": "e3-p4.checkQ",
      "checkA": "e3-p4.checkA",
      "vo": "e3-p4.vo",
      "art": "e3-p4.art"
    }
  },
  {
    "id": "e3-p5",
    "chapter": 3,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "quest",
          "meaning": [
            {
              "page": 9,
              "title": "停车",
              "points": 36
            },
            {
              "page": 11,
              "title": "行李",
              "points": 33
            },
            {
              "page": 2,
              "title": "入住",
              "points": 31
            }
          ],
          "sides": [
            {
              "a": "车",
              "b": "停车场",
              "aLabel": "车",
              "bLabel": "停车场",
              "points": 60
            },
            {
              "a": "游泳",
              "b": "游泳池",
              "aLabel": "游泳",
              "bLabel": "游泳池",
              "points": 80
            },
            {
              "a": "带狗",
              "b": "小狗",
              "aLabel": "带狗",
              "bLabel": "小狗",
              "points": 85
            }
          ],
          "wordMatch": 0,
          "gap": 3
        },
        "ja": {
          "kind": "quest",
          "meaning": [
            {
              "page": 9,
              "title": "Parking",
              "points": 36
            },
            {
              "page": 6,
              "title": "Swimming pool",
              "points": 32
            }
          ],
          "sides": [
            {
              "a": "park",
              "b": "parking",
              "aLabel": "park",
              "bLabel": "ちゅうしゃ〔parking〕",
              "points": 47
            },
            {
              "a": "swim",
              "b": "swimming",
              "aLabel": "およぐ〔swim〕",
              "bLabel": "およぎ〔swimming〕",
              "points": 97
            },
            {
              "a": "dog",
              "b": "dogs",
              "aLabel": "犬〔dog〕",
              "bLabel": "犬たち〔dogs〕",
              "points": 91
            }
          ],
          "wordMatch": 0,
          "gap": 4
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e3-p5.bubble",
      "aim": "e3-p5.aim",
      "look": "e3-p5.look",
      "action": "e3-p5.action",
      "summary": "e3-p5.summary",
      "talk": "e3-p5.talk",
      "checkQ": "e3-p5.checkQ",
      "checkA": "e3-p5.checkA",
      "vo": "e3-p5.vo",
      "art": "e3-p5.art"
    }
  },
  {
    "id": "e3-sum",
    "chapter": 3,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "每个词是从中心点出发的一根箭头。",
            "箭头先变一样长，只比方向。",
            "两根箭头的角越小，越近。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "語は、まん中の 点から のびる 1本の 矢。",
            "まず 矢の 長さを そろえ、むきだけ くらべる。",
            "2本の 矢の 角が 小さいほど 近い。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e3-sum.bubble",
      "aim": "e3-sum.aim",
      "look": "e3-sum.look",
      "action": "e3-sum.action",
      "summary": "e3-sum.summary",
      "talk": "e3-sum.talk",
      "checkQ": "e3-sum.checkQ",
      "checkA": "e3-sum.checkA",
      "vo": "e3-sum.vo",
      "art": "e3-sum.art",
      "star1": "e3-sum.star1",
      "star2": "e3-sum.star2",
      "star3": "e3-sum.star3"
    }
  },
  {
    "id": "e3-rev",
    "chapter": 3,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e3-rev.bubble",
      "aim": "e3-rev.aim",
      "look": "e3-rev.look",
      "action": "e3-rev.action",
      "summary": "e3-rev.summary",
      "talk": "e3-rev.talk",
      "checkQ": "e3-rev.checkQ",
      "checkA": "e3-rev.checkA",
      "vo": "e3-rev.vo",
      "art": "e3-rev.art",
      "star1": "e3-rev.star1",
      "star2": "e3-rev.star2",
      "star3": "e3-rev.star3"
    }
  },
  {
    "id": "e4-intro",
    "chapter": 4,
    "kind": "intro",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "shadow"
        },
        "ja": {
          "kind": "shadow"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e4-intro.bubble",
      "aim": "e4-intro.aim",
      "look": "e4-intro.look",
      "action": "e4-intro.action",
      "summary": "e4-intro.summary",
      "talk": "e4-intro.talk",
      "checkQ": "e4-intro.checkQ",
      "checkA": "e4-intro.checkA",
      "vo": "e4-intro.vo",
      "art": "e4-intro.art"
    }
  },
  {
    "id": "e4-p1",
    "chapter": 4,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rulers",
          "dim": 384
        },
        "ja": {
          "kind": "rulers",
          "dim": 384
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e4-p1.bubble",
      "aim": "e4-p1.aim",
      "look": "e4-p1.look",
      "action": "e4-p1.action",
      "summary": "e4-p1.summary",
      "talk": "e4-p1.talk",
      "checkQ": "e4-p1.checkQ",
      "checkA": "e4-p1.checkA",
      "vo": "e4-p1.vo",
      "art": "e4-p1.art"
    }
  },
  {
    "id": "e4-p2",
    "chapter": 4,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "squash",
          "count": 20
        },
        "ja": {
          "kind": "squash",
          "count": 20
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e4-p2.bubble",
      "aim": "e4-p2.aim",
      "look": "e4-p2.look",
      "action": "e4-p2.action",
      "summary": "e4-p2.summary",
      "talk": "e4-p2.talk",
      "checkQ": "e4-p2.checkQ",
      "checkA": "e4-p2.checkA",
      "vo": "e4-p2.vo",
      "art": "e4-p2.art"
    }
  },
  {
    "id": "e4-p3",
    "chapter": 4,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "lift",
          "mapKey": "zh",
          "items": [
            {
              "a": "狗",
              "b": "小狗",
              "aLabel": "狗",
              "bLabel": "小狗",
              "points": 97
            },
            {
              "a": "猫",
              "b": "入住",
              "aLabel": "猫",
              "bLabel": "入住",
              "points": 35
            }
          ]
        },
        "ja": {
          "kind": "lift",
          "mapKey": "en",
          "items": [
            {
              "a": "dog",
              "b": "dogs",
              "aLabel": "犬〔dog〕",
              "bLabel": "犬たち〔dogs〕",
              "points": 91
            },
            {
              "a": "dog",
              "b": "cat",
              "aLabel": "犬〔dog〕",
              "bLabel": "ねこ〔cat〕",
              "points": 30
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e4-p3.bubble",
      "aim": "e4-p3.aim",
      "look": "e4-p3.look",
      "action": "e4-p3.action",
      "summary": "e4-p3.summary",
      "talk": "e4-p3.talk",
      "checkQ": "e4-p3.checkQ",
      "checkA": "e4-p3.checkA",
      "vo": "e4-p3.vo",
      "art": "e4-p3.art"
    }
  },
  {
    "id": "e4-p4",
    "chapter": 4,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "trust",
          "mapKey": "zh",
          "items": [
            {
              "a": "狗",
              "b": "小狗",
              "aLabel": "狗",
              "bLabel": "小狗",
              "points": 97
            },
            {
              "a": "猫",
              "b": "入住",
              "aLabel": "猫",
              "bLabel": "入住",
              "points": 35
            }
          ]
        },
        "ja": {
          "kind": "trust",
          "mapKey": "en",
          "items": [
            {
              "a": "dog",
              "b": "dogs",
              "aLabel": "犬〔dog〕",
              "bLabel": "犬たち〔dogs〕",
              "points": 91
            },
            {
              "a": "dog",
              "b": "cat",
              "aLabel": "犬〔dog〕",
              "bLabel": "ねこ〔cat〕",
              "points": 30
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e4-p4.bubble",
      "aim": "e4-p4.aim",
      "look": "e4-p4.look",
      "action": "e4-p4.action",
      "summary": "e4-p4.summary",
      "talk": "e4-p4.talk",
      "checkQ": "e4-p4.checkQ",
      "checkA": "e4-p4.checkA",
      "vo": "e4-p4.vo",
      "art": "e4-p4.art"
    }
  },
  {
    "id": "e4-p5",
    "chapter": 4,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "fly",
          "items": [
            {
              "word": "早饭",
              "label": "早饭",
              "points": 67,
              "page": 4,
              "title": "早饭"
            },
            {
              "word": "游泳池",
              "label": "游泳池",
              "points": 61,
              "page": 6,
              "title": "游泳池"
            },
            {
              "word": "毛巾",
              "label": "毛巾",
              "points": 46,
              "page": 10,
              "title": "毛巾"
            }
          ]
        },
        "ja": {
          "kind": "fly",
          "items": [
            {
              "word": "breakfast",
              "label": "朝ごはん〔breakfast〕",
              "points": 69,
              "page": 4,
              "title": "Breakfast"
            },
            {
              "word": "swimming pool",
              "label": "水泳プール〔swimming pool〕",
              "points": 63,
              "page": 6,
              "title": "Swimming pool"
            },
            {
              "word": "towel",
              "label": "タオル〔towel〕",
              "points": 43,
              "page": 10,
              "title": "Towels"
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e4-p5.bubble",
      "aim": "e4-p5.aim",
      "look": "e4-p5.look",
      "action": "e4-p5.action",
      "summary": "e4-p5.summary",
      "talk": "e4-p5.talk",
      "checkQ": "e4-p5.checkQ",
      "checkA": "e4-p5.checkA",
      "vo": "e4-p5.vo",
      "art": "e4-p5.art"
    }
  },
  {
    "id": "e4-sum",
    "chapter": 4,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "纸上只有 2 根尺子，词的箭头住的地方有 384 根。",
            "地图是压扁的影子，原来摊开的样子留下不到一半。",
            "地图上挨着，不一定真的近（猫和入住只有 35 分）。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "紙には ものさしが 2本、語の 矢が いる 場所には 384本。",
            "地図は ぺちゃんこの かげ。もとの ひろがりかたは 半分も のこって いない。",
            "地図で となりでも、ほんとうに 近いとは かぎらない（犬 と ねこ 30てん）。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e4-sum.bubble",
      "aim": "e4-sum.aim",
      "look": "e4-sum.look",
      "action": "e4-sum.action",
      "summary": "e4-sum.summary",
      "talk": "e4-sum.talk",
      "checkQ": "e4-sum.checkQ",
      "checkA": "e4-sum.checkA",
      "vo": "e4-sum.vo",
      "art": "e4-sum.art",
      "star1": "e4-sum.star1",
      "star2": "e4-sum.star2",
      "star3": "e4-sum.star3"
    }
  },
  {
    "id": "e4-rev",
    "chapter": 4,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e4-rev.bubble",
      "aim": "e4-rev.aim",
      "look": "e4-rev.look",
      "action": "e4-rev.action",
      "summary": "e4-rev.summary",
      "talk": "e4-rev.talk",
      "checkQ": "e4-rev.checkQ",
      "checkA": "e4-rev.checkA",
      "vo": "e4-rev.vo",
      "art": "e4-rev.art",
      "star1": "e4-rev.star1",
      "star2": "e4-rev.star2",
      "star3": "e4-rev.star3"
    }
  },
  {
    "id": "e5-intro",
    "chapter": 5,
    "kind": "intro",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "twins"
        },
        "ja": {
          "kind": "twins"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e5-intro.bubble",
      "aim": "e5-intro.aim",
      "look": "e5-intro.look",
      "action": "e5-intro.action",
      "summary": "e5-intro.summary",
      "talk": "e5-intro.talk",
      "checkQ": "e5-intro.checkQ",
      "checkA": "e5-intro.checkA",
      "vo": "e5-intro.vo",
      "art": "e5-intro.art"
    }
  },
  {
    "id": "e5-p1",
    "chapter": 5,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rank",
          "focus": "猫",
          "word": "猫",
          "items": [
            {
              "word": "车位",
              "label": "车位",
              "points": 40
            },
            {
              "word": "小狗",
              "label": "小狗",
              "points": 39
            },
            {
              "word": "车",
              "label": "车",
              "points": 38
            }
          ],
          "also": 34
        },
        "ja": {
          "kind": "rank",
          "focus": "ねこ〔cat〕",
          "word": "cat",
          "items": [
            {
              "word": "car",
              "label": "車〔car〕",
              "points": 35
            },
            {
              "word": "dog",
              "label": "犬〔dog〕",
              "points": 30
            },
            {
              "word": "dogs",
              "label": "犬たち〔dogs〕",
              "points": 28
            }
          ],
          "also": 30
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e5-p1.bubble",
      "aim": "e5-p1.aim",
      "look": "e5-p1.look",
      "action": "e5-p1.action",
      "summary": "e5-p1.summary",
      "talk": "e5-p1.talk",
      "checkQ": "e5-p1.checkQ",
      "checkA": "e5-p1.checkA",
      "vo": "e5-p1.vo",
      "art": "e5-p1.art"
    }
  },
  {
    "id": "e5-p2",
    "chapter": 5,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rank",
          "focus": "停车",
          "word": "停车",
          "items": [
            {
              "word": "入住",
              "label": "入住",
              "points": 87
            },
            {
              "word": "退房",
              "label": "退房",
              "points": 78
            },
            {
              "word": "车位",
              "label": "车位",
              "points": 77
            },
            {
              "word": "停车场",
              "label": "停车场",
              "points": 73
            }
          ]
        },
        "ja": {
          "kind": "kana",
          "items": [
            {
              "a": "犬",
              "b": "dog",
              "aLabel": "犬",
              "bLabel": "犬〔dog〕",
              "points": 98
            },
            {
              "a": "いぬ",
              "b": "dog",
              "aLabel": "いぬ",
              "bLabel": "犬〔dog〕",
              "points": 35
            },
            {
              "a": "猫",
              "b": "cat",
              "aLabel": "猫",
              "bLabel": "ねこ〔cat〕",
              "points": 99
            },
            {
              "a": "ねこ",
              "b": "cat",
              "aLabel": "ねこ",
              "bLabel": "ねこ〔cat〕",
              "points": 40
            },
            {
              "a": "駐車場",
              "b": "parking lot",
              "aLabel": "駐車場",
              "bLabel": "ちゅうしゃじょう〔parking lot〕",
              "points": 91
            },
            {
              "a": "ちゅうしゃじょう",
              "b": "parking lot",
              "aLabel": "ちゅうしゃじょう",
              "bLabel": "ちゅうしゃじょう〔parking lot〕",
              "points": 22
            },
            {
              "a": "いぬ",
              "b": "犬",
              "aLabel": "いぬ",
              "bLabel": "犬",
              "points": 42
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e5-p2.bubble",
      "aim": "e5-p2.aim",
      "look": "e5-p2.look",
      "action": "e5-p2.action",
      "summary": "e5-p2.summary",
      "talk": "e5-p2.talk",
      "checkQ": "e5-p2.checkQ",
      "checkA": "e5-p2.checkA",
      "vo": "e5-p2.vo",
      "art": "e5-p2.art"
    }
  },
  {
    "id": "e5-p3",
    "chapter": 5,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "needles",
          "alone": [
            {
              "label": "失物招领",
              "page": 12,
              "points": 40
            },
            {
              "label": "行李",
              "page": 11,
              "points": 40
            },
            {
              "label": "入住",
              "page": 2,
              "points": 39
            }
          ],
          "sentence": [
            {
              "page": 9,
              "title": "停车",
              "points": 36
            }
          ],
          "line": 30,
          "gap": 3
        },
        "ja": {
          "kind": "needles",
          "alone": {
            "label": "車〔car〕",
            "page": 9,
            "points": 16
          },
          "sentence": [
            {
              "page": 9,
              "title": "Parking",
              "points": 36
            },
            {
              "page": 6,
              "title": "Swimming pool",
              "points": 32
            }
          ],
          "gap": 4
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e5-p3.bubble",
      "aim": "e5-p3.aim",
      "look": "e5-p3.look",
      "action": "e5-p3.action",
      "summary": "e5-p3.summary",
      "talk": "e5-p3.talk",
      "checkQ": "e5-p3.checkQ",
      "checkA": "e5-p3.checkA",
      "vo": "e5-p3.vo",
      "art": "e5-p3.art"
    }
  },
  {
    "id": "e5-p4",
    "chapter": 5,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "oldnew",
          "page": 4,
          "old": 74,
          "fresh": 74
        },
        "ja": {
          "kind": "oldnew",
          "page": 4,
          "old": 70,
          "fresh": 72
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e5-p4.bubble",
      "aim": "e5-p4.aim",
      "look": "e5-p4.look",
      "action": "e5-p4.action",
      "summary": "e5-p4.summary",
      "talk": "e5-p4.talk",
      "checkQ": "e5-p4.checkQ",
      "checkA": "e5-p4.checkA",
      "vo": "e5-p4.vo",
      "art": "e5-p4.art"
    }
  },
  {
    "id": "e5-p5",
    "chapter": 5,
    "kind": "page",
    "course": "embed",
    "quiz": true,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "看分不看地图",
            "最高分也会错",
            "问整句，多拿几张",
            "近不等于答案对"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "点数を 見る",
            "1いでも まちがう",
            "文で 聞いて 何まいも",
            "近くても 正解とは かぎらない"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e5-p5.bubble",
      "aim": "e5-p5.aim",
      "look": "e5-p5.look",
      "action": "e5-p5.action",
      "summary": "e5-p5.summary",
      "talk": "e5-p5.talk",
      "checkQ": "e5-p5.checkQ",
      "checkA": "e5-p5.checkA",
      "vo": "e5-p5.vo",
      "art": "e5-p5.art"
    }
  },
  {
    "id": "e5-sum",
    "chapter": 5,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "变数字的人也会认错：猫 离 车位 比离 小狗 还近 1 分。",
            "近分最高的邻居，不一定意思最像（停车 和 入住 87 分）。",
            "一个短词容易找错卡片；问得完整一点更好。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "数字に する 人も まちがえる：ねこ は 犬より 車に 5てん 近い。",
            "書きかたで 点数が かわる：犬 と dog 98てん、いぬ と dog 35てん。",
            "語 1つだと カードとの 点数が ひくい。文で 聞くと 点数が 上がるが、2いとの 差は 4てん だけ。だから カードは 何まいか とる。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e5-sum.bubble",
      "aim": "e5-sum.aim",
      "look": "e5-sum.look",
      "action": "e5-sum.action",
      "summary": "e5-sum.summary",
      "talk": "e5-sum.talk",
      "checkQ": "e5-sum.checkQ",
      "checkA": "e5-sum.checkA",
      "vo": "e5-sum.vo",
      "art": "e5-sum.art",
      "star1": "e5-sum.star1",
      "star2": "e5-sum.star2",
      "star3": "e5-sum.star3"
    }
  },
  {
    "id": "e5-rev",
    "chapter": 5,
    "kind": "summary",
    "course": "embed",
    "quiz": false,
    "visual": "embed",
    "shared": {
      "visual": "embed",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "e5-rev.bubble",
      "aim": "e5-rev.aim",
      "look": "e5-rev.look",
      "action": "e5-rev.action",
      "summary": "e5-rev.summary",
      "talk": "e5-rev.talk",
      "checkQ": "e5-rev.checkQ",
      "checkA": "e5-rev.checkA",
      "vo": "e5-rev.vo",
      "art": "e5-rev.art",
      "star1": "e5-rev.star1",
      "star2": "e5-rev.star2",
      "star3": "e5-rev.star3"
    }
  }
];

export const EMBED_TITLE = {
  "id": "etitle",
  "chapter": 0,
  "kind": "etitle",
  "course": "embed",
  "visual": "embed",
  "shared": {
    "visual": "embed"
  },
  "exampleSlots": null,
  "keys": {
    "bubble": "etitle.bubble",
    "aim": "etitle.aim",
    "look": "etitle.look",
    "action": "etitle.action",
    "summary": "etitle.summary",
    "checkQ": "etitle.checkQ",
    "checkA": "etitle.checkA",
    "vo": "etitle.vo"
  }
};
export const EMBED_END = {
  "id": "eend",
  "chapter": 0,
  "kind": "eend",
  "course": "embed",
  "visual": "embed",
  "shared": {
    "visual": "embed"
  },
  "exampleSlots": null,
  "keys": {
    "bubble": "eend.bubble",
    "aim": "eend.aim",
    "look": "eend.look",
    "action": "eend.action",
    "summary": "eend.summary",
    "checkQ": "eend.checkQ",
    "checkA": "eend.checkA",
    "vo": "eend.vo"
  }
};

export function embedPagesFor(chapter) {
  return EMBED_PAGES.filter((page) => page.chapter === chapter);
}
