/** Generated by game/scripts/build-rag-lesson.mjs. Picture numbers are copied from rag/demo JSON. */
export const RAG_PAGES = [
  {
    "id": "r1-intro",
    "chapter": 1,
    "kind": "intro",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "board",
          "covered": "今天的午饭",
          "open": "米饭和番茄炒蛋"
        },
        "ja": {
          "kind": "board",
          "covered": "きょうの きゅうしょく",
          "open": "ごはん"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-intro.bubble",
      "aim": "r1-intro.aim",
      "look": "r1-intro.look",
      "action": "r1-intro.action",
      "summary": "r1-intro.summary",
      "checkQ": "r1-intro.checkQ",
      "checkA": "r1-intro.checkA",
      "vo": "r1-intro.vo",
      "art": "r1-intro.art"
    }
  },
  {
    "id": "r1-p1",
    "chapter": 1,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "sign",
          "title": "星星酒店",
          "sub": "Hotel Hoshi"
        },
        "ja": {
          "kind": "sign",
          "title": "ホテル・ホシ",
          "sub": "Hotel Hoshi"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-p1.bubble",
      "aim": "r1-p1.aim",
      "look": "r1-p1.look",
      "action": "r1-p1.action",
      "summary": "r1-p1.summary",
      "checkQ": "r1-p1.checkQ",
      "checkA": "r1-p1.checkA",
      "vo": "r1-p1.vo",
      "art": "r1-p1.art"
    }
  },
  {
    "id": "r1-p2",
    "chapter": 1,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "memory",
          "line": "7:00–10:00",
          "caption": "脑袋里的旧话"
        },
        "ja": {
          "kind": "memory",
          "line": "7:00–10:00",
          "caption": "あたまの 中"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-p2.bubble",
      "aim": "r1-p2.aim",
      "look": "r1-p2.look",
      "action": "r1-p2.action",
      "summary": "r1-p2.summary",
      "checkQ": "r1-p2.checkQ",
      "checkA": "r1-p2.checkA",
      "vo": "r1-p2.vo",
      "art": "r1-p2.art"
    }
  },
  {
    "id": "r1-p3",
    "chapter": 1,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "book",
          "page": 4,
          "line": "早饭时间是早上6:30到9:30，在二楼的餐厅吃。",
          "badge": "今天的手册"
        },
        "ja": {
          "kind": "book",
          "page": 4,
          "line": "Breakfast is served from 6:30 AM to 9:30 AM in the restaurant on the 2nd floor.",
          "badge": "いまの 本"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-p3.bubble",
      "aim": "r1-p3.aim",
      "look": "r1-p3.look",
      "action": "r1-p3.action",
      "summary": "r1-p3.summary",
      "checkQ": "r1-p3.checkQ",
      "checkA": "r1-p3.checkA",
      "vo": "r1-p3.vo",
      "art": "r1-p3.art"
    }
  },
  {
    "id": "r1-p4",
    "chapter": 1,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "编的",
            "body": "1楼·24小时"
          },
          "right": {
            "title": "第6页",
            "body": "屋顶"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "つくった 話",
            "body": "1かい・24時間"
          },
          "right": {
            "title": "Page 6",
            "body": "おくじょう"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-p4.bubble",
      "aim": "r1-p4.aim",
      "look": "r1-p4.look",
      "action": "r1-p4.action",
      "summary": "r1-p4.summary",
      "checkQ": "r1-p4.checkQ",
      "checkA": "r1-p4.checkA",
      "vo": "r1-p4.vo",
      "art": "r1-p4.art"
    }
  },
  {
    "id": "r1-p5",
    "chapter": 1,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "重新练习",
            "body": "要很久"
          },
          "right": {
            "title": "换一页",
            "body": "马上"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "もういちど 練習",
            "body": "とても 長い"
          },
          "right": {
            "title": "ページを かえる",
            "body": "すぐ"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-p5.bubble",
      "aim": "r1-p5.aim",
      "look": "r1-p5.look",
      "action": "r1-p5.action",
      "summary": "r1-p5.summary",
      "checkQ": "r1-p5.checkQ",
      "checkA": "r1-p5.checkA",
      "vo": "r1-p5.vo",
      "art": "r1-p5.art"
    }
  },
  {
    "id": "r1-p6",
    "chapter": 1,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "flow",
          "steps": [
            "先查手册",
            "再回答"
          ]
        },
        "ja": {
          "kind": "flow",
          "steps": [
            "本を 見る",
            "こたえる"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-p6.bubble",
      "aim": "r1-p6.aim",
      "look": "r1-p6.look",
      "action": "r1-p6.action",
      "summary": "r1-p6.summary",
      "checkQ": "r1-p6.checkQ",
      "checkA": "r1-p6.checkA",
      "vo": "r1-p6.vo",
      "art": "r1-p6.art"
    }
  },
  {
    "id": "r1-p7",
    "chapter": 1,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "swap",
          "oldLine": "早饭时间是早上7:00到10:00，在二楼的餐厅吃。",
          "newLine": "早饭时间是早上6:30到9:30，在二楼的餐厅吃。"
        },
        "ja": {
          "kind": "swap",
          "oldLine": "Breakfast is served from 7:00 AM to 10:00 AM in the restaurant on the 2nd floor.",
          "newLine": "Breakfast is served from 6:30 AM to 9:30 AM in the restaurant on the 2nd floor."
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-p7.bubble",
      "aim": "r1-p7.aim",
      "look": "r1-p7.look",
      "action": "r1-p7.action",
      "summary": "r1-p7.summary",
      "checkQ": "r1-p7.checkQ",
      "checkA": "r1-p7.checkA",
      "vo": "r1-p7.vo",
      "art": "r1-p7.art"
    }
  },
  {
    "id": "r1-p8",
    "chapter": 1,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "cite",
          "page": 4,
          "line": "第4页"
        },
        "ja": {
          "kind": "cite",
          "page": 4,
          "line": "Page 4"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-p8.bubble",
      "aim": "r1-p8.aim",
      "look": "r1-p8.look",
      "action": "r1-p8.action",
      "summary": "r1-p8.summary",
      "checkQ": "r1-p8.checkQ",
      "checkA": "r1-p8.checkA",
      "vo": "r1-p8.vo",
      "art": "r1-p8.art"
    }
  },
  {
    "id": "r1-p9",
    "chapter": 1,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "hats",
          "page": 4,
          "line": "早饭时间是早上6:30到9:30，在二楼的餐厅吃。",
          "question": "早饭是几点？"
        },
        "ja": {
          "kind": "hats",
          "page": 4,
          "line": "Breakfast is served from 6:30 AM to 9:30 AM in the restaurant on the 2nd floor.",
          "question": "朝ごはんは 何時？"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-p9.bubble",
      "aim": "r1-p9.aim",
      "look": "r1-p9.look",
      "action": "r1-p9.action",
      "summary": "r1-p9.summary",
      "checkQ": "r1-p9.checkQ",
      "checkA": "r1-p9.checkA",
      "vo": "r1-p9.vo",
      "art": "r1-p9.art"
    }
  },
  {
    "id": "r1-sum",
    "chapter": 1,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "只靠记忆：会过时，没读过的会编（幻觉），改记忆要练很久。",
            "先查手册，再回答。还能说出在第几页。",
            "一个找，一个写，合起来叫 RAG。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "おぼえているだけ：古くなる、つくり話を する（ハルシネーション）、なおすのに 長い れんしゅう。",
            "まず あんないの 本を しらべて、それから こたえる。ページも 言える。",
            "さがし係 ＋ 書き係 ＝ RAG。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-sum.bubble",
      "aim": "r1-sum.aim",
      "look": "r1-sum.look",
      "action": "r1-sum.action",
      "summary": "r1-sum.summary",
      "checkQ": "r1-sum.checkQ",
      "checkA": "r1-sum.checkA",
      "vo": "r1-sum.vo",
      "art": "r1-sum.art",
      "star1": "r1-sum.star1",
      "star2": "r1-sum.star2",
      "star3": "r1-sum.star3"
    }
  },
  {
    "id": "r1-rev",
    "chapter": 1,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r1-rev.bubble",
      "aim": "r1-rev.aim",
      "look": "r1-rev.look",
      "action": "r1-rev.action",
      "summary": "r1-rev.summary",
      "checkQ": "r1-rev.checkQ",
      "checkA": "r1-rev.checkA",
      "vo": "r1-rev.vo",
      "art": "r1-rev.art",
      "star1": "r1-rev.star1",
      "star2": "r1-rev.star2",
      "star3": "r1-rev.star3"
    }
  },
  {
    "id": "r2-intro",
    "chapter": 2,
    "kind": "intro",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "大箱子",
            "body": "不好找"
          },
          "right": {
            "title": "小格子",
            "body": "一下就找到"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "大きな はこ",
            "body": "みつけにくい"
          },
          "right": {
            "title": "小さな はこ",
            "body": "すぐ"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-intro.bubble",
      "aim": "r2-intro.aim",
      "look": "r2-intro.look",
      "action": "r2-intro.action",
      "summary": "r2-intro.summary",
      "checkQ": "r2-intro.checkQ",
      "checkA": "r2-intro.checkA",
      "vo": "r2-intro.vo",
      "art": "r2-intro.art"
    }
  },
  {
    "id": "r2-p1",
    "chapter": 2,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "cards",
          "items": [
            {
              "page": 1,
              "title": "欢迎",
              "text": "欢迎来到星星酒店！前台24小时都有人。有什么问题，都可以问我们。"
            },
            {
              "page": 2,
              "title": "入住",
              "text": "下午3:00开始可以入住。请到前台告诉我们你的名字。"
            },
            {
              "page": 3,
              "title": "退房",
              "text": "退房时间是上午11:00。请把房间钥匙还给前台。"
            },
            {
              "page": 4,
              "title": "早饭",
              "text": "早饭时间是早上6:30到9:30，在二楼的餐厅吃。"
            },
            {
              "page": 5,
              "title": "晚饭",
              "text": "晚饭时间是晚上6:00到9:00，在二楼的餐厅吃。"
            },
            {
              "page": 6,
              "title": "游泳池",
              "text": "游泳池在屋顶上。夏天开放，时间是上午10:00到下午6:00。"
            },
            {
              "page": 7,
              "title": "大浴场",
              "text": "大浴场在一楼，开放时间是下午5:00到晚上11:00。"
            },
            {
              "page": 8,
              "title": "无线网",
              "text": "每个房间都能免费上无线网（Wi-Fi）。密码印在你的房卡上。"
            },
            {
              "page": 9,
              "title": "停车",
              "text": "停车场就在酒店旁边。停一晚要1000日元。"
            },
            {
              "page": 10,
              "title": "毛巾",
              "text": "多要的毛巾和枕头都是免费的。用房间里的电话打给前台就行。"
            },
            {
              "page": 11,
              "title": "行李",
              "text": "入住以前、退房以后，都可以把行李放在前台，我们帮你看着。"
            },
            {
              "page": 12,
              "title": "失物招领",
              "text": "东西丢了，请问前台。捡到的东西我们会保管一个月。"
            }
          ]
        },
        "ja": {
          "kind": "cards",
          "items": [
            {
              "page": 1,
              "title": "Welcome",
              "text": "Welcome to Hotel Hoshi. The front desk is open 24 hours. Please ask us anything."
            },
            {
              "page": 2,
              "title": "Check-in",
              "text": "Check-in time starts at 3:00 PM. Please tell us your name at the front desk."
            },
            {
              "page": 3,
              "title": "Checkout",
              "text": "Checkout time is 11:00 AM. Please give your room key back to the front desk."
            },
            {
              "page": 4,
              "title": "Breakfast",
              "text": "Breakfast is served from 6:30 AM to 9:30 AM in the restaurant on the 2nd floor."
            },
            {
              "page": 5,
              "title": "Dinner",
              "text": "Dinner is served from 6:00 PM to 9:00 PM in the restaurant on the 2nd floor."
            },
            {
              "page": 6,
              "title": "Swimming pool",
              "text": "The swimming pool is on the roof. It is open from 10:00 AM to 6:00 PM in summer."
            },
            {
              "page": 7,
              "title": "Big bath",
              "text": "The big bath is on the 1st floor. It is open from 5:00 PM to 11:00 PM."
            },
            {
              "page": 8,
              "title": "Wi-Fi",
              "text": "Free Wi-Fi works in every room. The password is printed on your room key card."
            },
            {
              "page": 9,
              "title": "Parking",
              "text": "The parking lot is next to the hotel. Parking costs 1,000 yen per night."
            },
            {
              "page": 10,
              "title": "Towels",
              "text": "Extra towels and pillows are free. Call the front desk from the phone in your room."
            },
            {
              "page": 11,
              "title": "Bags",
              "text": "We can keep your bags at the front desk before check-in and after checkout."
            },
            {
              "page": 12,
              "title": "Lost and found",
              "text": "If you lose something, ask the front desk. We keep lost things for one month."
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-p1.bubble",
      "aim": "r2-p1.aim",
      "look": "r2-p1.look",
      "action": "r2-p1.action",
      "summary": "r2-p1.summary",
      "checkQ": "r2-p1.checkQ",
      "checkA": "r2-p1.checkA",
      "vo": "r2-p1.vo",
      "art": "r2-p1.art"
    }
  },
  {
    "id": "r2-p2",
    "chapter": 2,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "big",
          "words": 167
        },
        "ja": {
          "kind": "big",
          "words": 186
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-p2.bubble",
      "aim": "r2-p2.aim",
      "look": "r2-p2.look",
      "action": "r2-p2.action",
      "summary": "r2-p2.summary",
      "checkQ": "r2-p2.checkQ",
      "checkA": "r2-p2.checkA",
      "vo": "r2-p2.vo",
      "art": "r2-p2.art"
    }
  },
  {
    "id": "r2-p3",
    "chapter": 2,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "cards",
          "items": [
            {
              "page": 1,
              "title": "欢迎",
              "text": "欢迎来到星星酒店！前台24小时都有人。有什么问题，都可以问我们。"
            },
            {
              "page": 2,
              "title": "入住",
              "text": "下午3:00开始可以入住。请到前台告诉我们你的名字。"
            },
            {
              "page": 3,
              "title": "退房",
              "text": "退房时间是上午11:00。请把房间钥匙还给前台。"
            },
            {
              "page": 4,
              "title": "早饭",
              "text": "早饭时间是早上6:30到9:30，在二楼的餐厅吃。"
            },
            {
              "page": 5,
              "title": "晚饭",
              "text": "晚饭时间是晚上6:00到9:00，在二楼的餐厅吃。"
            },
            {
              "page": 6,
              "title": "游泳池",
              "text": "游泳池在屋顶上。夏天开放，时间是上午10:00到下午6:00。"
            },
            {
              "page": 7,
              "title": "大浴场",
              "text": "大浴场在一楼，开放时间是下午5:00到晚上11:00。"
            },
            {
              "page": 8,
              "title": "无线网",
              "text": "每个房间都能免费上无线网（Wi-Fi）。密码印在你的房卡上。"
            },
            {
              "page": 9,
              "title": "停车",
              "text": "停车场就在酒店旁边。停一晚要1000日元。"
            },
            {
              "page": 10,
              "title": "毛巾",
              "text": "多要的毛巾和枕头都是免费的。用房间里的电话打给前台就行。"
            },
            {
              "page": 11,
              "title": "行李",
              "text": "入住以前、退房以后，都可以把行李放在前台，我们帮你看着。"
            },
            {
              "page": 12,
              "title": "失物招领",
              "text": "东西丢了，请问前台。捡到的东西我们会保管一个月。"
            }
          ],
          "cut": true
        },
        "ja": {
          "kind": "cards",
          "items": [
            {
              "page": 1,
              "title": "Welcome",
              "text": "Welcome to Hotel Hoshi. The front desk is open 24 hours. Please ask us anything."
            },
            {
              "page": 2,
              "title": "Check-in",
              "text": "Check-in time starts at 3:00 PM. Please tell us your name at the front desk."
            },
            {
              "page": 3,
              "title": "Checkout",
              "text": "Checkout time is 11:00 AM. Please give your room key back to the front desk."
            },
            {
              "page": 4,
              "title": "Breakfast",
              "text": "Breakfast is served from 6:30 AM to 9:30 AM in the restaurant on the 2nd floor."
            },
            {
              "page": 5,
              "title": "Dinner",
              "text": "Dinner is served from 6:00 PM to 9:00 PM in the restaurant on the 2nd floor."
            },
            {
              "page": 6,
              "title": "Swimming pool",
              "text": "The swimming pool is on the roof. It is open from 10:00 AM to 6:00 PM in summer."
            },
            {
              "page": 7,
              "title": "Big bath",
              "text": "The big bath is on the 1st floor. It is open from 5:00 PM to 11:00 PM."
            },
            {
              "page": 8,
              "title": "Wi-Fi",
              "text": "Free Wi-Fi works in every room. The password is printed on your room key card."
            },
            {
              "page": 9,
              "title": "Parking",
              "text": "The parking lot is next to the hotel. Parking costs 1,000 yen per night."
            },
            {
              "page": 10,
              "title": "Towels",
              "text": "Extra towels and pillows are free. Call the front desk from the phone in your room."
            },
            {
              "page": 11,
              "title": "Bags",
              "text": "We can keep your bags at the front desk before check-in and after checkout."
            },
            {
              "page": 12,
              "title": "Lost and found",
              "text": "If you lose something, ask the front desk. We keep lost things for one month."
            }
          ],
          "cut": true
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-p3.bubble",
      "aim": "r2-p3.aim",
      "look": "r2-p3.look",
      "action": "r2-p3.action",
      "summary": "r2-p3.summary",
      "checkQ": "r2-p3.checkQ",
      "checkA": "r2-p3.checkA",
      "vo": "r2-p3.vo",
      "art": "r2-p3.art"
    }
  },
  {
    "id": "r2-p4",
    "chapter": 2,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "counts",
          "min": 9,
          "max": 18,
          "focus": 12
        },
        "ja": {
          "kind": "counts",
          "min": 14,
          "max": 18,
          "focus": 15
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-p4.bubble",
      "aim": "r2-p4.aim",
      "look": "r2-p4.look",
      "action": "r2-p4.action",
      "summary": "r2-p4.summary",
      "checkQ": "r2-p4.checkQ",
      "checkA": "r2-p4.checkA",
      "vo": "r2-p4.vo",
      "art": "r2-p4.art"
    }
  },
  {
    "id": "r2-p5",
    "chapter": 2,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "cards",
          "items": [
            {
              "page": 1,
              "title": "欢迎",
              "text": "欢迎来到星星酒店！前台24小时都有人。有什么问题，都可以问我们。"
            },
            {
              "page": 2,
              "title": "入住",
              "text": "下午3:00开始可以入住。请到前台告诉我们你的名字。"
            },
            {
              "page": 3,
              "title": "退房",
              "text": "退房时间是上午11:00。请把房间钥匙还给前台。"
            },
            {
              "page": 4,
              "title": "早饭",
              "text": "早饭时间是早上6:30到9:30，在二楼的餐厅吃。"
            },
            {
              "page": 5,
              "title": "晚饭",
              "text": "晚饭时间是晚上6:00到9:00，在二楼的餐厅吃。"
            },
            {
              "page": 6,
              "title": "游泳池",
              "text": "游泳池在屋顶上。夏天开放，时间是上午10:00到下午6:00。"
            },
            {
              "page": 7,
              "title": "大浴场",
              "text": "大浴场在一楼，开放时间是下午5:00到晚上11:00。"
            },
            {
              "page": 8,
              "title": "无线网",
              "text": "每个房间都能免费上无线网（Wi-Fi）。密码印在你的房卡上。"
            },
            {
              "page": 9,
              "title": "停车",
              "text": "停车场就在酒店旁边。停一晚要1000日元。"
            },
            {
              "page": 10,
              "title": "毛巾",
              "text": "多要的毛巾和枕头都是免费的。用房间里的电话打给前台就行。"
            },
            {
              "page": 11,
              "title": "行李",
              "text": "入住以前、退房以后，都可以把行李放在前台，我们帮你看着。"
            },
            {
              "page": 12,
              "title": "失物招领",
              "text": "东西丢了，请问前台。捡到的东西我们会保管一个月。"
            }
          ],
          "labeled": true
        },
        "ja": {
          "kind": "cards",
          "items": [
            {
              "page": 1,
              "title": "Welcome",
              "text": "Welcome to Hotel Hoshi. The front desk is open 24 hours. Please ask us anything."
            },
            {
              "page": 2,
              "title": "Check-in",
              "text": "Check-in time starts at 3:00 PM. Please tell us your name at the front desk."
            },
            {
              "page": 3,
              "title": "Checkout",
              "text": "Checkout time is 11:00 AM. Please give your room key back to the front desk."
            },
            {
              "page": 4,
              "title": "Breakfast",
              "text": "Breakfast is served from 6:30 AM to 9:30 AM in the restaurant on the 2nd floor."
            },
            {
              "page": 5,
              "title": "Dinner",
              "text": "Dinner is served from 6:00 PM to 9:00 PM in the restaurant on the 2nd floor."
            },
            {
              "page": 6,
              "title": "Swimming pool",
              "text": "The swimming pool is on the roof. It is open from 10:00 AM to 6:00 PM in summer."
            },
            {
              "page": 7,
              "title": "Big bath",
              "text": "The big bath is on the 1st floor. It is open from 5:00 PM to 11:00 PM."
            },
            {
              "page": 8,
              "title": "Wi-Fi",
              "text": "Free Wi-Fi works in every room. The password is printed on your room key card."
            },
            {
              "page": 9,
              "title": "Parking",
              "text": "The parking lot is next to the hotel. Parking costs 1,000 yen per night."
            },
            {
              "page": 10,
              "title": "Towels",
              "text": "Extra towels and pillows are free. Call the front desk from the phone in your room."
            },
            {
              "page": 11,
              "title": "Bags",
              "text": "We can keep your bags at the front desk before check-in and after checkout."
            },
            {
              "page": 12,
              "title": "Lost and found",
              "text": "If you lose something, ask the front desk. We keep lost things for one month."
            }
          ],
          "labeled": true
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-p5.bubble",
      "aim": "r2-p5.aim",
      "look": "r2-p5.look",
      "action": "r2-p5.action",
      "summary": "r2-p5.summary",
      "checkQ": "r2-p5.checkQ",
      "checkA": "r2-p5.checkA",
      "vo": "r2-p5.vo",
      "art": "r2-p5.art"
    }
  },
  {
    "id": "r2-p6",
    "chapter": 2,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "夏天开放",
            "body": "什么开放？"
          },
          "right": {
            "title": "Page 6",
            "body": "游泳池"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "It is open",
            "body": "それ？"
          },
          "right": {
            "title": "Page 6",
            "body": "Swimming pool"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-p6.bubble",
      "aim": "r2-p6.aim",
      "look": "r2-p6.look",
      "action": "r2-p6.action",
      "summary": "r2-p6.summary",
      "checkQ": "r2-p6.checkQ",
      "checkA": "r2-p6.checkA",
      "vo": "r2-p6.vo",
      "art": "r2-p6.art"
    }
  },
  {
    "id": "r2-p7",
    "chapter": 2,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "flow",
          "steps": [
            "100个词",
            "切一段"
          ]
        },
        "ja": {
          "kind": "flow",
          "steps": [
            "100語",
            "1くぎり"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-p7.bubble",
      "aim": "r2-p7.aim",
      "look": "r2-p7.look",
      "action": "r2-p7.action",
      "summary": "r2-p7.summary",
      "checkQ": "r2-p7.checkQ",
      "checkA": "r2-p7.checkA",
      "vo": "r2-p7.vo",
      "art": "r2-p7.art"
    }
  },
  {
    "id": "r2-p8",
    "chapter": 2,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "sign",
          "title": "卡片盒",
          "sub": "12张"
        },
        "ja": {
          "kind": "sign",
          "title": "カードばこ",
          "sub": "12まい"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-p8.bubble",
      "aim": "r2-p8.aim",
      "look": "r2-p8.look",
      "action": "r2-p8.action",
      "summary": "r2-p8.summary",
      "checkQ": "r2-p8.checkQ",
      "checkA": "r2-p8.checkA",
      "vo": "r2-p8.vo",
      "art": "r2-p8.art"
    }
  },
  {
    "id": "r2-p9",
    "chapter": 2,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "卡片上的字",
            "body": "能看能改"
          },
          "right": {
            "title": "记忆",
            "body": "改不了一句"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "カードの 字",
            "body": "読める・直せる"
          },
          "right": {
            "title": "きおく",
            "body": "1文 直せない"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-p9.bubble",
      "aim": "r2-p9.aim",
      "look": "r2-p9.look",
      "action": "r2-p9.action",
      "summary": "r2-p9.summary",
      "checkQ": "r2-p9.checkQ",
      "checkA": "r2-p9.checkA",
      "vo": "r2-p9.vo",
      "art": "r2-p9.art"
    }
  },
  {
    "id": "r2-sum",
    "chapter": 2,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "整本当一张卡，说不出答案在哪一页。",
            "按页剪成 12 张卡，一张讲一件事，贴上页码。剪太碎也不行。",
            "卡片放进卡片盒。卡片上的字，人能看也能改。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "まるごと 1まいだと、何ページか 言えない。",
            "ページごとに 12まいに 切る。1まい 1つの こと、ページばんごうつき。切りすぎも だめ。",
            "カードは カードばこへ。人が 読めて、書きなおせる。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-sum.bubble",
      "aim": "r2-sum.aim",
      "look": "r2-sum.look",
      "action": "r2-sum.action",
      "summary": "r2-sum.summary",
      "checkQ": "r2-sum.checkQ",
      "checkA": "r2-sum.checkA",
      "vo": "r2-sum.vo",
      "art": "r2-sum.art",
      "star1": "r2-sum.star1",
      "star2": "r2-sum.star2",
      "star3": "r2-sum.star3"
    }
  },
  {
    "id": "r2-rev",
    "chapter": 2,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r2-rev.bubble",
      "aim": "r2-rev.aim",
      "look": "r2-rev.look",
      "action": "r2-rev.action",
      "summary": "r2-rev.summary",
      "checkQ": "r2-rev.checkQ",
      "checkA": "r2-rev.checkA",
      "vo": "r2-rev.vo",
      "art": "r2-rev.art",
      "star1": "r2-rev.star1",
      "star2": "r2-rev.star2",
      "star3": "r2-rev.star3"
    }
  },
  {
    "id": "r3-intro",
    "chapter": 3,
    "kind": "intro",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "问题",
            "body": "?"
          },
          "right": {
            "title": "朋友卡",
            "body": "★"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "しつもん",
            "body": "?"
          },
          "right": {
            "title": "ともだちカード",
            "body": "★"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-intro.bubble",
      "aim": "r3-intro.aim",
      "look": "r3-intro.look",
      "action": "r3-intro.action",
      "summary": "r3-intro.summary",
      "checkQ": "r3-intro.checkQ",
      "checkA": "r3-intro.checkA",
      "vo": "r3-intro.vo",
      "art": "r3-intro.art"
    }
  },
  {
    "id": "r3-p1",
    "chapter": 3,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "flow",
          "steps": [
            "12张打分",
            "挑分高的"
          ]
        },
        "ja": {
          "kind": "flow",
          "steps": [
            "12まいに 点",
            "高い カード"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-p1.bubble",
      "aim": "r3-p1.aim",
      "look": "r3-p1.look",
      "action": "r3-p1.action",
      "summary": "r3-p1.summary",
      "checkQ": "r3-p1.checkQ",
      "checkA": "r3-p1.checkA",
      "vo": "r3-p1.vo",
      "art": "r3-p1.art"
    }
  },
  {
    "id": "r3-p2",
    "chapter": 3,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "chips",
          "chips": [
            {
              "text": "几点",
              "on": false
            },
            {
              "text": "退房",
              "on": true
            }
          ]
        },
        "ja": {
          "kind": "chips",
          "chips": [
            {
              "text": "What",
              "on": false
            },
            {
              "text": "time",
              "on": true
            },
            {
              "text": "is",
              "on": false
            },
            {
              "text": "checkout",
              "on": true
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-p2.bubble",
      "aim": "r3-p2.aim",
      "look": "r3-p2.look",
      "action": "r3-p2.action",
      "summary": "r3-p2.summary",
      "checkQ": "r3-p2.checkQ",
      "checkA": "r3-p2.checkA",
      "vo": "r3-p2.vo",
      "art": "r3-p2.art"
    }
  },
  {
    "id": "r3-p3",
    "chapter": 3,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "shares",
          "boards": [
            {
              "page": 3,
              "title": "退房",
              "score": 35,
              "words": [
                {
                  "text": "还给",
                  "share": 0.41,
                  "hot": false
                },
                {
                  "text": "钥匙",
                  "share": 0.41,
                  "hot": false
                },
                {
                  "text": "11",
                  "share": 0.352,
                  "hot": false
                },
                {
                  "text": "上午",
                  "share": 0.352,
                  "hot": false
                },
                {
                  "text": "退房",
                  "share": 0.352,
                  "hot": true
                },
                {
                  "text": "房间",
                  "share": 0.311,
                  "hot": false
                },
                {
                  "text": "时间",
                  "share": 0.279,
                  "hot": false
                },
                {
                  "text": "00",
                  "share": 0.253,
                  "hot": false
                },
                {
                  "text": "前台",
                  "share": 0.231,
                  "hot": false
                }
              ]
            },
            {
              "page": 11,
              "title": "行李",
              "score": 31,
              "words": [
                {
                  "text": "以前",
                  "share": 0.358,
                  "hot": false
                },
                {
                  "text": "以后",
                  "share": 0.358,
                  "hot": false
                },
                {
                  "text": "帮",
                  "share": 0.358,
                  "hot": false
                },
                {
                  "text": "放在",
                  "share": 0.358,
                  "hot": false
                },
                {
                  "text": "看着",
                  "share": 0.358,
                  "hot": false
                },
                {
                  "text": "行李",
                  "share": 0.358,
                  "hot": false
                },
                {
                  "text": "入住",
                  "share": 0.308,
                  "hot": false
                },
                {
                  "text": "退房",
                  "share": 0.308,
                  "hot": true
                },
                {
                  "text": "前台",
                  "share": 0.202,
                  "hot": false
                }
              ]
            }
          ]
        },
        "ja": {
          "kind": "shares",
          "boards": [
            {
              "page": 3,
              "title": "Checkout",
              "score": 59,
              "words": [
                {
                  "text": "11",
                  "share": 0.418,
                  "hot": false
                },
                {
                  "text": "checkout",
                  "share": 0.418,
                  "hot": true
                },
                {
                  "text": "key",
                  "share": 0.418,
                  "hot": false
                },
                {
                  "text": "time",
                  "share": 0.418,
                  "hot": true
                },
                {
                  "text": "room",
                  "share": 0.369,
                  "hot": false
                },
                {
                  "text": "00",
                  "share": 0.3,
                  "hot": false
                },
                {
                  "text": "desk",
                  "share": 0.274,
                  "hot": false
                }
              ]
            },
            {
              "page": 11,
              "title": "Bags",
              "score": 36,
              "words": [
                {
                  "text": "bags",
                  "share": 0.598,
                  "hot": false
                },
                {
                  "text": "check",
                  "share": 0.514,
                  "hot": false
                },
                {
                  "text": "checkout",
                  "share": 0.514,
                  "hot": true
                },
                {
                  "text": "desk",
                  "share": 0.337,
                  "hot": false
                }
              ]
            },
            {
              "page": 2,
              "title": "Check-in",
              "score": 28,
              "words": [
                {
                  "text": "starts",
                  "share": 0.464,
                  "hot": false
                },
                {
                  "text": "tell",
                  "share": 0.464,
                  "hot": false
                },
                {
                  "text": "check",
                  "share": 0.399,
                  "hot": false
                },
                {
                  "text": "time",
                  "share": 0.399,
                  "hot": true
                },
                {
                  "text": "pm",
                  "share": 0.316,
                  "hot": false
                },
                {
                  "text": "00",
                  "share": 0.287,
                  "hot": false
                },
                {
                  "text": "desk",
                  "share": 0.262,
                  "hot": false
                }
              ]
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-p3.bubble",
      "aim": "r3-p3.aim",
      "look": "r3-p3.look",
      "action": "r3-p3.action",
      "summary": "r3-p3.summary",
      "checkQ": "r3-p3.checkQ",
      "checkA": "r3-p3.checkA",
      "vo": "r3-p3.vo",
      "art": "r3-p3.art"
    }
  },
  {
    "id": "r3-p4",
    "chapter": 3,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "zeros",
          "n": 12
        },
        "ja": {
          "kind": "bars",
          "items": [
            {
              "page": 3,
              "score": 42,
              "title": "Checkout",
              "hot": true
            },
            {
              "page": 2,
              "score": 40,
              "title": "Check-in",
              "hot": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-p4.bubble",
      "aim": "r3-p4.aim",
      "look": "r3-p4.look",
      "action": "r3-p4.action",
      "summary": "r3-p4.summary",
      "checkQ": "r3-p4.checkQ",
      "checkA": "r3-p4.checkA",
      "vo": "r3-p4.vo",
      "art": "r3-p4.art"
    }
  },
  {
    "id": "r3-p5",
    "chapter": 3,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "address",
          "n": 384
        },
        "ja": {
          "kind": "address",
          "n": 384
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-p5.bubble",
      "aim": "r3-p5.aim",
      "look": "r3-p5.look",
      "action": "r3-p5.action",
      "summary": "r3-p5.summary",
      "checkQ": "r3-p5.checkQ",
      "checkA": "r3-p5.checkA",
      "vo": "r3-p5.vo",
      "art": "r3-p5.art"
    }
  },
  {
    "id": "r3-p6",
    "chapter": 3,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "bars",
          "items": [
            {
              "page": 6,
              "score": 53,
              "title": "游泳池",
              "hot": true
            },
            {
              "page": 7,
              "score": 37,
              "title": "大浴场",
              "hot": false
            },
            {
              "page": 2,
              "score": 24,
              "title": "入住",
              "hot": false
            }
          ]
        },
        "ja": {
          "kind": "bars",
          "items": [
            {
              "page": 6,
              "score": 53,
              "title": "Swimming pool",
              "hot": true
            },
            {
              "page": 2,
              "score": 33,
              "title": "Check-in",
              "hot": false
            },
            {
              "page": 7,
              "score": 32,
              "title": "Big bath",
              "hot": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-p6.bubble",
      "aim": "r3-p6.aim",
      "look": "r3-p6.look",
      "action": "r3-p6.action",
      "summary": "r3-p6.summary",
      "checkQ": "r3-p6.checkQ",
      "checkA": "r3-p6.checkA",
      "vo": "r3-p6.vo",
      "art": "r3-p6.art"
    }
  },
  {
    "id": "r3-p7",
    "chapter": 3,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "bars",
          "items": [
            {
              "page": 4,
              "score": 74,
              "title": "早饭",
              "hot": true
            },
            {
              "page": 2,
              "score": 45,
              "title": "入住",
              "hot": false
            },
            {
              "page": 5,
              "score": 39,
              "title": "晚饭",
              "hot": false
            }
          ]
        },
        "ja": {
          "kind": "bars",
          "items": [
            {
              "page": 4,
              "score": 72,
              "title": "Breakfast",
              "hot": true
            },
            {
              "page": 2,
              "score": 52,
              "title": "Check-in",
              "hot": false
            },
            {
              "page": 3,
              "score": 43,
              "title": "Checkout",
              "hot": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-p7.bubble",
      "aim": "r3-p7.aim",
      "look": "r3-p7.look",
      "action": "r3-p7.action",
      "summary": "r3-p7.summary",
      "checkQ": "r3-p7.checkQ",
      "checkA": "r3-p7.checkA",
      "vo": "r3-p7.vo",
      "art": "r3-p7.art"
    }
  },
  {
    "id": "r3-p8",
    "chapter": 3,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "flow",
          "steps": [
            "卡片的地址",
            "地址簿",
            "只算问题"
          ]
        },
        "ja": {
          "kind": "flow",
          "steps": [
            "カードの 住所",
            "じゅうしょちょう",
            "しつもんだけ"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-p8.bubble",
      "aim": "r3-p8.aim",
      "look": "r3-p8.look",
      "action": "r3-p8.action",
      "summary": "r3-p8.summary",
      "checkQ": "r3-p8.checkQ",
      "checkA": "r3-p8.checkA",
      "vo": "r3-p8.vo",
      "art": "r3-p8.art"
    }
  },
  {
    "id": "r3-p9",
    "chapter": 3,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "hats",
          "note": "在蓝帽子里"
        },
        "ja": {
          "kind": "hats",
          "note": "青ぼうしの 中"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-p9.bubble",
      "aim": "r3-p9.aim",
      "look": "r3-p9.look",
      "action": "r3-p9.action",
      "summary": "r3-p9.summary",
      "checkQ": "r3-p9.checkQ",
      "checkA": "r3-p9.checkA",
      "vo": "r3-p9.vo",
      "art": "r3-p9.art"
    }
  },
  {
    "id": "r3-sum",
    "chapter": 3,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "找卡片＝给每张卡打分，拿分最高的前 3 张。",
            "先切成词再数一样的词：简单，可是词不一样（游泳 ≠ 游泳池）就找不到。",
            "意思的地址：意思像就近，分越高越近。地址先算好抄进地址簿（索引）。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "カードさがし ＝ どの カードにも 点数、上から 3まい とる。",
            "同じ 語を かぞえる：かんたん。でも 字が ちがうと 見つからない。",
            "いみの じゅうしょ：いみが にて いれば 近く、点数が 高い。じゅうしょは じゅうしょちょう（インデックス）に うつして おく。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-sum.bubble",
      "aim": "r3-sum.aim",
      "look": "r3-sum.look",
      "action": "r3-sum.action",
      "summary": "r3-sum.summary",
      "checkQ": "r3-sum.checkQ",
      "checkA": "r3-sum.checkA",
      "vo": "r3-sum.vo",
      "art": "r3-sum.art",
      "star1": "r3-sum.star1",
      "star2": "r3-sum.star2",
      "star3": "r3-sum.star3"
    }
  },
  {
    "id": "r3-rev",
    "chapter": 3,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r3-rev.bubble",
      "aim": "r3-rev.aim",
      "look": "r3-rev.look",
      "action": "r3-rev.action",
      "summary": "r3-rev.summary",
      "checkQ": "r3-rev.checkQ",
      "checkA": "r3-rev.checkA",
      "vo": "r3-rev.vo",
      "art": "r3-rev.art",
      "star1": "r3-rev.star1",
      "star2": "r3-rev.star2",
      "star3": "r3-rev.star3"
    }
  },
  {
    "id": "r4-intro",
    "chapter": 4,
    "kind": "intro",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "看着课本",
            "body": "更准"
          },
          "right": {
            "title": "不看",
            "body": "靠猜"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "本を 見る",
            "body": "あたりやすい"
          },
          "right": {
            "title": "見ない",
            "body": "あてる"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-intro.bubble",
      "aim": "r4-intro.aim",
      "look": "r4-intro.look",
      "action": "r4-intro.action",
      "summary": "r4-intro.summary",
      "checkQ": "r4-intro.checkQ",
      "checkA": "r4-intro.checkA",
      "vo": "r4-intro.vo",
      "art": "r4-intro.art"
    }
  },
  {
    "id": "r4-p1",
    "chapter": 4,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "bars",
          "items": [
            {
              "page": 4,
              "score": 74,
              "title": "早饭",
              "hot": true
            },
            {
              "page": 2,
              "score": 45,
              "title": "入住",
              "hot": false
            },
            {
              "page": 5,
              "score": 39,
              "title": "晚饭",
              "hot": false
            }
          ]
        },
        "ja": {
          "kind": "bars",
          "items": [
            {
              "page": 4,
              "score": 72,
              "title": "Breakfast",
              "hot": true
            },
            {
              "page": 2,
              "score": 52,
              "title": "Check-in",
              "hot": false
            },
            {
              "page": 3,
              "score": 43,
              "title": "Checkout",
              "hot": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-p1.bubble",
      "aim": "r4-p1.aim",
      "look": "r4-p1.look",
      "action": "r4-p1.action",
      "summary": "r4-p1.summary",
      "checkQ": "r4-p1.checkQ",
      "checkA": "r4-p1.checkA",
      "vo": "r4-p1.vo",
      "art": "r4-p1.art"
    }
  },
  {
    "id": "r4-p2",
    "chapter": 4,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "join",
          "question": "早饭是几点？",
          "items": [
            {
              "page": 4,
              "score": 74,
              "title": "早饭",
              "hot": true
            },
            {
              "page": 2,
              "score": 45,
              "title": "入住",
              "hot": false
            },
            {
              "page": 5,
              "score": 39,
              "title": "晚饭",
              "hot": false
            }
          ]
        },
        "ja": {
          "kind": "join",
          "question": "What time is breakfast?",
          "items": [
            {
              "page": 4,
              "score": 72,
              "title": "Breakfast",
              "hot": true
            },
            {
              "page": 2,
              "score": 52,
              "title": "Check-in",
              "hot": false
            },
            {
              "page": 3,
              "score": 43,
              "title": "Checkout",
              "hot": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-p2.bubble",
      "aim": "r4-p2.aim",
      "look": "r4-p2.look",
      "action": "r4-p2.action",
      "summary": "r4-p2.summary",
      "checkQ": "r4-p2.checkQ",
      "checkA": "r4-p2.checkA",
      "vo": "r4-p2.vo",
      "art": "r4-p2.art"
    }
  },
  {
    "id": "r4-p3",
    "chapter": 4,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "flow",
          "steps": [
            "一个字",
            "再一个字"
          ]
        },
        "ja": {
          "kind": "flow",
          "steps": [
            "一文字",
            "また 一文字"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-p3.bubble",
      "aim": "r4-p3.aim",
      "look": "r4-p3.look",
      "action": "r4-p3.action",
      "summary": "r4-p3.summary",
      "checkQ": "r4-p3.checkQ",
      "checkA": "r4-p3.checkA",
      "vo": "r4-p3.vo",
      "art": "r4-p3.art"
    }
  },
  {
    "id": "r4-p4",
    "chapter": 4,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "cite",
          "page": 4,
          "line": "只搬第1张"
        },
        "ja": {
          "kind": "cite",
          "page": 4,
          "line": "1まいめだけ"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-p4.bubble",
      "aim": "r4-p4.aim",
      "look": "r4-p4.look",
      "action": "r4-p4.action",
      "summary": "r4-p4.summary",
      "checkQ": "r4-p4.checkQ",
      "checkA": "r4-p4.checkA",
      "vo": "r4-p4.vo",
      "art": "r4-p4.art"
    }
  },
  {
    "id": "r4-p5",
    "chapter": 4,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "bars",
          "items": [
            {
              "page": 4,
              "score": 76,
              "title": "早饭",
              "hot": true
            },
            {
              "page": 5,
              "score": 54,
              "title": "晚饭",
              "hot": false
            },
            {
              "page": 2,
              "score": 39,
              "title": "入住",
              "hot": false
            }
          ]
        },
        "ja": {
          "kind": "bars",
          "items": [
            {
              "page": 4,
              "score": 74,
              "title": "Breakfast",
              "hot": true
            },
            {
              "page": 5,
              "score": 55,
              "title": "Dinner",
              "hot": false
            },
            {
              "page": 2,
              "score": 47,
              "title": "Check-in",
              "hot": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-p5.bubble",
      "aim": "r4-p5.aim",
      "look": "r4-p5.look",
      "action": "r4-p5.action",
      "summary": "r4-p5.summary",
      "checkQ": "r4-p5.checkQ",
      "checkA": "r4-p5.checkA",
      "vo": "r4-p5.vo",
      "art": "r4-p5.art"
    }
  },
  {
    "id": "r4-p6",
    "chapter": 4,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "cite",
          "page": 4,
          "line": "根据第 4 页（早饭）：早饭时间是早上6:30到9:30，在二楼的餐厅吃。"
        },
        "ja": {
          "kind": "cite",
          "page": 4,
          "line": "According to Page 4 (Breakfast): Breakfast is served from 6:30 AM to 9:30 AM in the restaurant on the 2nd floor."
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-p6.bubble",
      "aim": "r4-p6.aim",
      "look": "r4-p6.look",
      "action": "r4-p6.action",
      "summary": "r4-p6.summary",
      "checkQ": "r4-p6.checkQ",
      "checkA": "r4-p6.checkA",
      "vo": "r4-p6.vo",
      "art": "r4-p6.art"
    }
  },
  {
    "id": "r4-p7",
    "chapter": 4,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "cite",
          "page": 4,
          "line": "第4页"
        },
        "ja": {
          "kind": "cite",
          "page": 4,
          "line": "Page 4"
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-p7.bubble",
      "aim": "r4-p7.aim",
      "look": "r4-p7.look",
      "action": "r4-p7.action",
      "summary": "r4-p7.summary",
      "checkQ": "r4-p7.checkQ",
      "checkA": "r4-p7.checkA",
      "vo": "r4-p7.vo",
      "art": "r4-p7.art"
    }
  },
  {
    "id": "r4-p8",
    "chapter": 4,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "查过再答",
            "body": "更常是真的"
          },
          "right": {
            "title": "只靠记忆",
            "body": "会编"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "本を 見た",
            "body": "より ほんとう"
          },
          "right": {
            "title": "きおくだけ",
            "body": "はずれる"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-p8.bubble",
      "aim": "r4-p8.aim",
      "look": "r4-p8.look",
      "action": "r4-p8.action",
      "summary": "r4-p8.summary",
      "checkQ": "r4-p8.checkQ",
      "checkA": "r4-p8.checkA",
      "vo": "r4-p8.vo",
      "art": "r4-p8.art"
    }
  },
  {
    "id": "r4-p9",
    "chapter": 4,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "flow",
          "steps": [
            "问",
            "找",
            "接上",
            "写",
            "第几页"
          ]
        },
        "ja": {
          "kind": "bars",
          "items": [
            {
              "page": 6,
              "score": 57,
              "title": "Swimming pool",
              "hot": true
            },
            {
              "page": 7,
              "score": 36,
              "title": "Big bath",
              "hot": false
            },
            {
              "page": 9,
              "score": 19,
              "title": "Parking",
              "hot": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-p9.bubble",
      "aim": "r4-p9.aim",
      "look": "r4-p9.look",
      "action": "r4-p9.action",
      "summary": "r4-p9.summary",
      "checkQ": "r4-p9.checkQ",
      "checkA": "r4-p9.checkA",
      "vo": "r4-p9.vo",
      "art": "r4-p9.art"
    }
  },
  {
    "id": "r4-sum",
    "chapter": 4,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "问题 + 找到的卡片，接在一起交给写回答的助手。",
            "它还是一个字一个字往下写，要用对得上的卡，也能合用几张卡。",
            "游戏里用填空纸（模板）搬第 1 张卡的原话，不会挑卡，并说出第几页。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "しつもん ＋ 見つけた カードを つなげて 書き係へ。",
            "書き係は 1語ずつ つないで 書く。あう カードを つかい、何まいかを あわせる ことも できる。",
            "ゲームでは あなうめの 紙（テンプレート）で 1まいめの 文を はこぶ。えらべない。ページを 言う。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-sum.bubble",
      "aim": "r4-sum.aim",
      "look": "r4-sum.look",
      "action": "r4-sum.action",
      "summary": "r4-sum.summary",
      "checkQ": "r4-sum.checkQ",
      "checkA": "r4-sum.checkA",
      "vo": "r4-sum.vo",
      "art": "r4-sum.art",
      "star1": "r4-sum.star1",
      "star2": "r4-sum.star2",
      "star3": "r4-sum.star3"
    }
  },
  {
    "id": "r4-rev",
    "chapter": 4,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r4-rev.bubble",
      "aim": "r4-rev.aim",
      "look": "r4-rev.look",
      "action": "r4-rev.action",
      "summary": "r4-rev.summary",
      "checkQ": "r4-rev.checkQ",
      "checkA": "r4-rev.checkA",
      "vo": "r4-rev.vo",
      "art": "r4-rev.art",
      "star1": "r4-rev.star1",
      "star2": "r4-rev.star2",
      "star3": "r4-rev.star3"
    }
  },
  {
    "id": "r5-intro",
    "chapter": 5,
    "kind": "intro",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "手册里有",
            "body": "○"
          },
          "right": {
            "title": "手册里没有",
            "body": "×"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "本に ある",
            "body": "○"
          },
          "right": {
            "title": "本に ない",
            "body": "×"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-intro.bubble",
      "aim": "r5-intro.aim",
      "look": "r5-intro.look",
      "action": "r5-intro.action",
      "summary": "r5-intro.summary",
      "checkQ": "r5-intro.checkQ",
      "checkA": "r5-intro.checkA",
      "vo": "r5-intro.vo",
      "art": "r5-intro.art"
    }
  },
  {
    "id": "r5-p1",
    "chapter": 5,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "zeros",
          "n": 12
        },
        "ja": {
          "kind": "bars",
          "items": [
            {
              "page": 3,
              "score": 27,
              "title": "Checkout",
              "hot": true
            },
            {
              "page": 4,
              "score": 27,
              "title": "Breakfast",
              "hot": false
            },
            {
              "page": 2,
              "score": 26,
              "title": "Check-in",
              "hot": false
            }
          ],
          "hair": true
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-p1.bubble",
      "aim": "r5-p1.aim",
      "look": "r5-p1.look",
      "action": "r5-p1.action",
      "summary": "r5-p1.summary",
      "checkQ": "r5-p1.checkQ",
      "checkA": "r5-p1.checkA",
      "vo": "r5-p1.vo",
      "art": "r5-p1.art"
    }
  },
  {
    "id": "r5-p2",
    "chapter": 5,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "停车",
            "body": "第9页 · 36"
          },
          "right": {
            "title": "游泳",
            "body": "第6页 · 53"
          }
        },
        "ja": {
          "kind": "take",
          "one": {
            "page": 3,
            "score": 27,
            "title": "Checkout",
            "hot": true
          },
          "many": [
            {
              "page": 3,
              "score": 27,
              "title": "Checkout",
              "hot": true
            },
            {
              "page": 4,
              "score": 27,
              "title": "Breakfast",
              "hot": false
            },
            {
              "page": 2,
              "score": 26,
              "title": "Check-in",
              "hot": false
            }
          ],
          "pick": 4,
          "carry": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-p2.bubble",
      "aim": "r5-p2.aim",
      "look": "r5-p2.look",
      "action": "r5-p2.action",
      "summary": "r5-p2.summary",
      "checkQ": "r5-p2.checkQ",
      "checkA": "r5-p2.checkA",
      "vo": "r5-p2.vo",
      "art": "r5-p2.art"
    }
  },
  {
    "id": "r5-p3",
    "chapter": 5,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "bars",
          "items": [
            {
              "page": 9,
              "score": 36,
              "title": "停车",
              "hot": true
            },
            {
              "page": 11,
              "score": 33,
              "title": "行李",
              "hot": false
            },
            {
              "page": 2,
              "score": 31,
              "title": "入住",
              "hot": false
            }
          ]
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "朝ごはん",
            "body": "Page 4 · 72"
          },
          "right": {
            "title": "park",
            "body": "Page 9 · 36"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-p3.bubble",
      "aim": "r5-p3.aim",
      "look": "r5-p3.look",
      "action": "r5-p3.action",
      "summary": "r5-p3.summary",
      "checkQ": "r5-p3.checkQ",
      "checkA": "r5-p3.checkA",
      "vo": "r5-p3.vo",
      "art": "r5-p3.art"
    }
  },
  {
    "id": "r5-p4",
    "chapter": 5,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "line",
          "items": [
            {
              "page": 12,
              "score": 28,
              "title": "失物招领",
              "hot": true
            },
            {
              "page": 11,
              "score": 21,
              "title": "行李",
              "hot": false
            },
            {
              "page": 3,
              "score": 16,
              "title": "退房",
              "hot": false
            }
          ],
          "meaningLine": 30,
          "wordLine": 10
        },
        "ja": {
          "kind": "line",
          "items": [
            {
              "page": 1,
              "score": 16,
              "title": "Welcome",
              "hot": true
            },
            {
              "page": 12,
              "score": 15,
              "title": "Lost and found",
              "hot": false
            },
            {
              "page": 10,
              "score": 12,
              "title": "Towels",
              "hot": false
            }
          ],
          "meaningLine": 20,
          "wordLine": 10
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-p4.bubble",
      "aim": "r5-p4.aim",
      "look": "r5-p4.look",
      "action": "r5-p4.action",
      "summary": "r5-p4.summary",
      "checkQ": "r5-p4.checkQ",
      "checkA": "r5-p4.checkA",
      "vo": "r5-p4.vo",
      "art": "r5-p4.art"
    }
  },
  {
    "id": "r5-p5",
    "chapter": 5,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "cite",
          "page": 0,
          "line": "我不知道。我没找到分数过线的卡片。请问问酒店的工作人员。"
        },
        "ja": {
          "kind": "cite",
          "page": 0,
          "line": "I don't know. I found no card with a score over the line. Please ask a hotel staff member."
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-p5.bubble",
      "aim": "r5-p5.aim",
      "look": "r5-p5.look",
      "action": "r5-p5.action",
      "summary": "r5-p5.summary",
      "checkQ": "r5-p5.checkQ",
      "checkA": "r5-p5.checkA",
      "vo": "r5-p5.vo",
      "art": "r5-p5.art"
    }
  },
  {
    "id": "r5-p6",
    "chapter": 5,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "bars",
          "items": [
            {
              "page": 13,
              "score": 37,
              "title": "宠物",
              "hot": true
            },
            {
              "page": 12,
              "score": 28,
              "title": "失物招领",
              "hot": false
            },
            {
              "page": 11,
              "score": 21,
              "title": "行李",
              "hot": false
            }
          ]
        },
        "ja": {
          "kind": "bars",
          "items": [
            {
              "page": 13,
              "score": 27,
              "title": "Pets",
              "hot": true
            },
            {
              "page": 1,
              "score": 16,
              "title": "Welcome",
              "hot": false
            },
            {
              "page": 12,
              "score": 15,
              "title": "Lost and found",
              "hot": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-p6.bubble",
      "aim": "r5-p6.aim",
      "look": "r5-p6.look",
      "action": "r5-p6.action",
      "summary": "r5-p6.summary",
      "checkQ": "r5-p6.checkQ",
      "checkA": "r5-p6.checkA",
      "vo": "r5-p6.vo",
      "art": "r5-p6.art"
    }
  },
  {
    "id": "r5-p7",
    "chapter": 5,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "bars",
          "items": [
            {
              "page": 4,
              "score": 74,
              "title": "早饭",
              "hot": true
            },
            {
              "page": 2,
              "score": 45,
              "title": "入住",
              "hot": false
            },
            {
              "page": 5,
              "score": 39,
              "title": "晚饭",
              "hot": false
            }
          ]
        },
        "ja": {
          "kind": "bars",
          "items": [
            {
              "page": 4,
              "score": 70,
              "title": "Breakfast",
              "hot": true
            },
            {
              "page": 2,
              "score": 52,
              "title": "Check-in",
              "hot": false
            },
            {
              "page": 3,
              "score": 43,
              "title": "Checkout",
              "hot": false
            }
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-p7.bubble",
      "aim": "r5-p7.aim",
      "look": "r5-p7.look",
      "action": "r5-p7.action",
      "summary": "r5-p7.summary",
      "checkQ": "r5-p7.checkQ",
      "checkA": "r5-p7.checkA",
      "vo": "r5-p7.vo",
      "art": "r5-p7.art"
    }
  },
  {
    "id": "r5-p8",
    "chapter": 5,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "pair",
          "left": {
            "title": "手册写错",
            "body": "回答也错"
          },
          "right": {
            "title": "把手册改对",
            "body": "马上能用"
          }
        },
        "ja": {
          "kind": "pair",
          "left": {
            "title": "本が まちがい",
            "body": "こたえも まちがい"
          },
          "right": {
            "title": "本を 直す",
            "body": "すぐ 使える"
          }
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-p8.bubble",
      "aim": "r5-p8.aim",
      "look": "r5-p8.look",
      "action": "r5-p8.action",
      "summary": "r5-p8.summary",
      "checkQ": "r5-p8.checkQ",
      "checkA": "r5-p8.checkA",
      "vo": "r5-p8.vo",
      "art": "r5-p8.art"
    }
  },
  {
    "id": "r5-p9",
    "chapter": 5,
    "kind": "page",
    "course": "rag",
    "quiz": true,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": []
        },
        "ja": {
          "kind": "rules",
          "lines": []
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-p9.bubble",
      "aim": "r5-p9.aim",
      "look": "r5-p9.look",
      "action": "r5-p9.action",
      "summary": "r5-p9.summary",
      "checkQ": "r5-p9.checkQ",
      "checkA": "r5-p9.checkA",
      "vo": "r5-p9.vo",
      "art": "r5-p9.art"
    }
  },
  {
    "id": "r5-sum",
    "chapter": 5,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "rules",
          "lines": [
            "找卡片也会出错（手册里有，却没找到）；按意思找更准；第 1 名赢得不多时，多拿几张更保险。",
            "第 1 名比线低＝这个办法没找到；按意思找也找不到，就老实说「我不知道」。过了线也不一定是对的卡。",
            "加卡、换卡，马上就变，不用重新练习。卡片写错，回答也错。"
          ]
        },
        "ja": {
          "kind": "rules",
          "lines": [
            "1いでも まちがう。何まいか とると たすかる。いみで さがすと もっと よい。",
            "1いが 線より ひくい ＝ この やり方では 見つからなかった。いみで さがしても ないときは、正直に「わかりません」。線を こえても 正しいとは かぎらない。",
            "カードを ふやす・とりかえると すぐ かわる。れんしゅうは いらない。カードが まちがえば こたえも まちがう。"
          ]
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-sum.bubble",
      "aim": "r5-sum.aim",
      "look": "r5-sum.look",
      "action": "r5-sum.action",
      "summary": "r5-sum.summary",
      "checkQ": "r5-sum.checkQ",
      "checkA": "r5-sum.checkA",
      "vo": "r5-sum.vo",
      "art": "r5-sum.art",
      "star1": "r5-sum.star1",
      "star2": "r5-sum.star2",
      "star3": "r5-sum.star3"
    }
  },
  {
    "id": "r5-rev",
    "chapter": 5,
    "kind": "summary",
    "course": "rag",
    "quiz": false,
    "visual": "rag",
    "shared": {
      "visual": "rag",
      "locales": {
        "zh": {
          "kind": "stars",
          "n": 3
        },
        "ja": {
          "kind": "stars",
          "n": 3
        }
      }
    },
    "exampleSlots": null,
    "keys": {
      "bubble": "r5-rev.bubble",
      "aim": "r5-rev.aim",
      "look": "r5-rev.look",
      "action": "r5-rev.action",
      "summary": "r5-rev.summary",
      "checkQ": "r5-rev.checkQ",
      "checkA": "r5-rev.checkA",
      "vo": "r5-rev.vo",
      "art": "r5-rev.art",
      "star1": "r5-rev.star1",
      "star2": "r5-rev.star2",
      "star3": "r5-rev.star3"
    }
  }
];

export const RAG_TITLE = {
  "id": "rtitle",
  "chapter": 0,
  "kind": "rtitle",
  "course": "rag",
  "visual": "rag",
  "shared": {
    "visual": "rag"
  },
  "exampleSlots": null,
  "keys": {
    "bubble": "rtitle.bubble",
    "aim": "rtitle.aim",
    "look": "rtitle.look",
    "action": "rtitle.action",
    "summary": "rtitle.summary",
    "checkQ": "rtitle.checkQ",
    "checkA": "rtitle.checkA",
    "vo": "rtitle.vo"
  }
};
export const RAG_END = {
  "id": "rend",
  "chapter": 0,
  "kind": "rend",
  "course": "rag",
  "visual": "rag",
  "shared": {
    "visual": "rag"
  },
  "exampleSlots": null,
  "keys": {
    "bubble": "rend.bubble",
    "aim": "rend.aim",
    "look": "rend.look",
    "action": "rend.action",
    "summary": "rend.summary",
    "checkQ": "rend.checkQ",
    "checkA": "rend.checkA",
    "vo": "rend.vo"
  }
};

export function ragPagesFor(chapter) {
  return RAG_PAGES.filter((page) => page.chapter === chapter);
}
